// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package resolvers

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type APIToken struct {
	ID               string `json:"id"`
	ServiceAccountID string `json:"serviceAccountId"`
	Scope            string `json:"scope"`
	ExpiresAtUnix    int    `json:"expiresAtUnix"`
	RevokedAtUnix    int    `json:"revokedAtUnix"`
	LastUsedAtUnix   int    `json:"lastUsedAtUnix"`
	CreatedBy        string `json:"createdBy"`
}

type ApprovalComment struct {
	ID           string `json:"id"`
	AuthorUserID string `json:"authorUserId"`
	AuthorName   string `json:"authorName"`
	Body         string `json:"body"`
	CreatedAt    string `json:"createdAt"`
}

type ApprovalRequest struct {
	ID                 string             `json:"id"`
	SecretID           string             `json:"secretId"`
	RequestedByUserID  string             `json:"requestedByUserId"`
	Status             ApprovalStatus     `json:"status"`
	RequestedAt        string             `json:"requestedAt"`
	Reason             *string            `json:"reason,omitempty"`
	ResolvedAt         *string            `json:"resolvedAt,omitempty"`
	ResolvedByUserID   *string            `json:"resolvedByUserId,omitempty"`
	ResolvedByUserName *string            `json:"resolvedByUserName,omitempty"`
	Comments           []*ApprovalComment `json:"comments"`
	Kind               RequestKind        `json:"kind"`
	FolderID           string             `json:"folderId"`
	DestParentID       string             `json:"destParentId"`
	FolderName         string             `json:"folderName"`
	DestParentName     string             `json:"destParentName"`
}

type AuditAttr struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type AuditChainStatus struct {
	Valid       bool `json:"valid"`
	BrokenAtSeq int  `json:"brokenAtSeq"`
	Length      int  `json:"length"`
}

type AuditRecord struct {
	Seq         int          `json:"seq"`
	Tier        string       `json:"tier"`
	Action      string       `json:"action"`
	ActorUserID string       `json:"actorUserId"`
	ActorName   string       `json:"actorName"`
	Subject     string       `json:"subject"`
	GroupID     string       `json:"groupId"`
	Sensitive   bool         `json:"sensitive"`
	Attributes  []*AuditAttr `json:"attributes"`
	OccurredAt  string       `json:"occurredAt"`
	PrevHash    string       `json:"prevHash"`
	Hash        string       `json:"hash"`
}

type CertExport struct {
	FileBase64  string `json:"fileBase64"`
	Filename    string `json:"filename"`
	ContentType string `json:"contentType"`
}

type CertMeta struct {
	Subject           string   `json:"subject"`
	Issuer            string   `json:"issuer"`
	Sans              []string `json:"sans"`
	NotBefore         string   `json:"notBefore"`
	NotAfter          string   `json:"notAfter"`
	SerialNumber      string   `json:"serialNumber"`
	FingerprintSha256 string   `json:"fingerprintSha256"`
	KeyAlgorithm      string   `json:"keyAlgorithm"`
	KeyBits           int      `json:"keyBits"`
	IsCa              bool     `json:"isCA"`
	HasPrivateKey     bool     `json:"hasPrivateKey"`
}

type ComponentVersion struct {
	Name         string             `json:"name"`
	Version      *string            `json:"version,omitempty"`
	Commit       *string            `json:"commit,omitempty"`
	Status       ComponentStatus    `json:"status"`
	Dependencies []*DependencyState `json:"dependencies,omitempty"`
}

type Connection struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Protocol    string  `json:"protocol"`
	Port        *int    `json:"port,omitempty"`
	UseTLS      *bool   `json:"useTls,omitempty"`
	Description *string `json:"description,omitempty"`
	TargetCount int     `json:"targetCount"`
}

type ConnectionInput struct {
	ID          *string `json:"id,omitempty"`
	Name        string  `json:"name"`
	Protocol    string  `json:"protocol"`
	Port        *int    `json:"port,omitempty"`
	UseTLS      *bool   `json:"useTls,omitempty"`
	Description *string `json:"description,omitempty"`
}

type CreateSecretInput struct {
	Name      string           `json:"name"`
	FolderID  string           `json:"folderId"`
	TypeID    string           `json:"typeId"`
	TargetID  *string          `json:"targetId,omitempty"`
	ExpiresAt *string          `json:"expiresAt,omitempty"`
	Fields    []*KeyValueInput `json:"fields"`
}

type DecideSecretUsesResult struct {
	Outcomes []*SecretUseOutcome `json:"outcomes"`
}

type DependencyState struct {
	Name     string           `json:"name"`
	State    DependencyHealth `json:"state"`
	Required bool             `json:"required"`
	Error    *string          `json:"error,omitempty"`
	Version  *string          `json:"version,omitempty"`
}

type Diagnostics struct {
	GeneratedAt string              `json:"generatedAt"`
	TraceID     string              `json:"traceId"`
	Actor       *DiagnosticsActor   `json:"actor"`
	PublicURL   string              `json:"publicUrl"`
	Appliance   *string             `json:"appliance,omitempty"`
	Gateway     *ComponentVersion   `json:"gateway"`
	Services    []*ComponentVersion `json:"services"`
	ThirdParty  []*ComponentVersion `json:"thirdParty"`
}

type DiagnosticsActor struct {
	ID       string   `json:"id"`
	Username string   `json:"username"`
	Roles    []string `json:"roles"`
}

type FactorInput struct {
	Kind              string  `json:"kind"`
	Code              *string `json:"code,omitempty"`
	CredentialJSON    *string `json:"credentialJson,omitempty"`
	WebauthnSessionID *string `json:"webauthnSessionId,omitempty"`
}

type Folder struct {
	ID                 string      `json:"id"`
	Name               string      `json:"name"`
	ParentID           *string     `json:"parentId,omitempty"`
	Scope              FolderScope `json:"scope"`
	OwnerUserID        *string     `json:"ownerUserId,omitempty"`
	GroupID            *string     `json:"groupId,omitempty"`
	Role               *string     `json:"role,omitempty"`
	IsMasterPersonal   *bool       `json:"isMasterPersonal,omitempty"`
	Order              *int        `json:"order,omitempty"`
	SubtreeSecretCount *int        `json:"subtreeSecretCount,omitempty"`
	Owners             []string    `json:"owners,omitempty"`
	CanManage          bool        `json:"canManage"`
	RevealStepUp       StepUpMode  `json:"revealStepUp"`
}

type FolderAccess struct {
	Read          bool `json:"read"`
	Reveal        bool `json:"reveal"`
	Manage        bool `json:"manage"`
	Approve       bool `json:"approve"`
	Informed      bool `json:"informed"`
	ManageRuleset bool `json:"manageRuleset"`
}

type FolderAccessRule struct {
	ID          string      `json:"id"`
	FolderID    string      `json:"folderId"`
	SubjectKind SubjectKind `json:"subjectKind"`
	SubjectID   string      `json:"subjectId"`
	Role        FolderRole  `json:"role"`
}

type FolderRuleset struct {
	FolderID        string               `json:"folderId"`
	Owners          []string             `json:"owners"`
	Rules           []*RaciRule          `json:"rules"`
	Inherited       []*InheritedRaciRule `json:"inherited"`
	InheritedOwners []*InheritedOwner    `json:"inheritedOwners"`
}

type Group struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type ImportCertificateResult struct {
	Secret  *Secret   `json:"secret,omitempty"`
	Aliases []string  `json:"aliases"`
	Meta    *CertMeta `json:"meta,omitempty"`
}

type InheritedFolderRule struct {
	Rule           *FolderAccessRule `json:"rule"`
	FromFolderID   string            `json:"fromFolderId"`
	FromFolderName string            `json:"fromFolderName"`
}

type InheritedOwner struct {
	UserID         string `json:"userId"`
	FromFolderID   string `json:"fromFolderId"`
	FromFolderName string `json:"fromFolderName"`
}

type InheritedRaciRule struct {
	Rule           *RaciRule `json:"rule"`
	FromFolderID   string    `json:"fromFolderId"`
	FromFolderName string    `json:"fromFolderName"`
}

type KeyPair struct {
	PrivateKey string `json:"privateKey"`
	PublicKey  string `json:"publicKey"`
}

type KeyValue struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type KeyValueInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Lease struct {
	ID        string `json:"id"`
	SecretID  string `json:"secretId"`
	UserID    string `json:"userId"`
	IssuedAt  string `json:"issuedAt"`
	ExpiresAt string `json:"expiresAt"`
	Returned  *bool  `json:"returned,omitempty"`
}

type Maintenance struct {
	ReadOnly bool    `json:"readOnly"`
	Reason   *string `json:"reason,omitempty"`
}

type MintAPITokenResult struct {
	Token    string    `json:"token"`
	APIToken *APIToken `json:"apiToken"`
}

type Mutation struct {
}

type Notification struct {
	ID            string `json:"id"`
	Action        string `json:"action"`
	ResourceKind  string `json:"resourceKind"`
	ResourceID    string `json:"resourceId"`
	ResourceLabel string `json:"resourceLabel"`
	ActorLabel    string `json:"actorLabel"`
	OccurredAt    string `json:"occurredAt"`
	Read          bool   `json:"read"`
}

type PasskeyChallenge struct {
	Options           string `json:"options"`
	WebauthnSessionID string `json:"webauthnSessionId"`
}

type PasswordPolicy struct {
	ID            string        `json:"id"`
	Name          string        `json:"name"`
	MinLength     int           `json:"minLength"`
	MaxLength     *int          `json:"maxLength,omitempty"`
	RequireUpper  bool          `json:"requireUpper"`
	RequireLower  bool          `json:"requireLower"`
	RequireDigit  bool          `json:"requireDigit"`
	RequireSymbol bool          `json:"requireSymbol"`
	RotationDays  *int          `json:"rotationDays,omitempty"`
	StartClass    *PwStartClass `json:"startClass,omitempty"`
	EndLiteral    *string       `json:"endLiteral,omitempty"`
	ExcludeChars  *string       `json:"excludeChars,omitempty"`
	IsDefault     bool          `json:"isDefault"`
	ByTypeFields  int           `json:"byTypeFields"`
	Deletable     bool          `json:"deletable"`
}

type PasswordPolicyInput struct {
	ID            *string       `json:"id,omitempty"`
	Name          string        `json:"name"`
	MinLength     int           `json:"minLength"`
	MaxLength     *int          `json:"maxLength,omitempty"`
	RequireUpper  bool          `json:"requireUpper"`
	RequireLower  bool          `json:"requireLower"`
	RequireDigit  bool          `json:"requireDigit"`
	RequireSymbol bool          `json:"requireSymbol"`
	RotationDays  *int          `json:"rotationDays,omitempty"`
	StartClass    *PwStartClass `json:"startClass,omitempty"`
	EndLiteral    *string       `json:"endLiteral,omitempty"`
	ExcludeChars  *string       `json:"excludeChars,omitempty"`
}

type Query struct {
}

type RaciDecision struct {
	Read           bool   `json:"read"`
	ReadReason     string `json:"readReason"`
	Reveal         bool   `json:"reveal"`
	RevealReason   string `json:"revealReason"`
	Manage         bool   `json:"manage"`
	ManageReason   string `json:"manageReason"`
	Approve        bool   `json:"approve"`
	ApproveReason  string `json:"approveReason"`
	Informed       bool   `json:"informed"`
	InformedReason string `json:"informedReason"`
}

type RaciRule struct {
	ID          string           `json:"id"`
	FolderID    string           `json:"folderId"`
	Order       int              `json:"order"`
	SubjectKind SubjectKind      `json:"subjectKind"`
	SubjectName string           `json:"subjectName"`
	SubjectID   *string          `json:"subjectId,omitempty"`
	Grants      []*RaciRuleGrant `json:"grants"`
}

type RaciRuleGrant struct {
	Action RaciAction `json:"action"`
	Value  RaciGrant  `json:"value"`
}

type RaciRuleGrantInput struct {
	Action RaciAction `json:"action"`
	Value  RaciGrant  `json:"value"`
}

type RaciRuleInput struct {
	SubjectKind SubjectKind           `json:"subjectKind"`
	SubjectName string                `json:"subjectName"`
	SubjectID   *string               `json:"subjectId,omitempty"`
	Grants      []*RaciRuleGrantInput `json:"grants"`
}

type Secret struct {
	ID                   string           `json:"id"`
	Name                 string           `json:"name"`
	FolderID             string           `json:"folderId"`
	TypeID               string           `json:"typeId"`
	TargetID             *string          `json:"targetId,omitempty"`
	ExpiresAt            *string          `json:"expiresAt,omitempty"`
	LastHeartbeatResult  *HeartbeatResult `json:"lastHeartbeatResult,omitempty"`
	VerifiedAt           *string          `json:"verifiedAt,omitempty"`
	Masked               *bool            `json:"masked,omitempty"`
	ViewCount            *int             `json:"viewCount,omitempty"`
	LastAccessedAt       *string          `json:"lastAccessedAt,omitempty"`
	Retired              bool             `json:"retired"`
	RetiredAt            string           `json:"retiredAt"`
	LastRotationResult   *RotationState   `json:"lastRotationResult,omitempty"`
	RotatedAt            *string          `json:"rotatedAt,omitempty"`
	RotationIntervalDays *int             `json:"rotationIntervalDays,omitempty"`
	NextRotationAt       *string          `json:"nextRotationAt,omitempty"`
	RotationOptOut       *bool            `json:"rotationOptOut,omitempty"`
	HeartbeatOptOut      *bool            `json:"heartbeatOptOut,omitempty"`
	RequireTokenApproval *bool            `json:"requireTokenApproval,omitempty"`
	CanRead              *bool            `json:"canRead,omitempty"`
}

type SecretFieldDef struct {
	Key               string             `json:"key"`
	Label             string             `json:"label"`
	Kind              FieldKind          `json:"kind"`
	Options           []string           `json:"options,omitempty"`
	DefaultValue      *string            `json:"defaultValue,omitempty"`
	Required          *bool              `json:"required,omitempty"`
	Sensitive         *bool              `json:"sensitive,omitempty"`
	PolicyID          *string            `json:"policyId,omitempty"`
	PolicyEnforcement *PolicyEnforcement `json:"policyEnforcement,omitempty"`
	Rotates           *bool              `json:"rotates,omitempty"`
	SuperSensitive    *bool              `json:"superSensitive,omitempty"`
	Pattern           *string            `json:"pattern,omitempty"`
	MaxLength         *int               `json:"maxLength,omitempty"`
}

type SecretFieldDefInput struct {
	Key               string             `json:"key"`
	Label             string             `json:"label"`
	Kind              FieldKind          `json:"kind"`
	Options           []string           `json:"options,omitempty"`
	DefaultValue      *string            `json:"defaultValue,omitempty"`
	Required          *bool              `json:"required,omitempty"`
	Sensitive         *bool              `json:"sensitive,omitempty"`
	PolicyID          *string            `json:"policyId,omitempty"`
	PolicyEnforcement *PolicyEnforcement `json:"policyEnforcement,omitempty"`
	Rotates           *bool              `json:"rotates,omitempty"`
	SuperSensitive    *bool              `json:"superSensitive,omitempty"`
	Pattern           *string            `json:"pattern,omitempty"`
	MaxLength         *int               `json:"maxLength,omitempty"`
}

type SecretRuleset struct {
	SecretID  string               `json:"secretId"`
	Rules     []*RaciRule          `json:"rules"`
	Inherited []*InheritedRaciRule `json:"inherited"`
}

type SecretStats struct {
	Total        int `json:"total"`
	ExpiringSoon int `json:"expiringSoon"`
	Expired      int `json:"expired"`
	Drift        int `json:"drift"`
}

type SecretType struct {
	ID        string            `json:"id"`
	Name      string            `json:"name"`
	Fields    []*SecretFieldDef `json:"fields"`
	Heartbeat *bool             `json:"heartbeat,omitempty"`
	Checkout  *bool             `json:"checkout,omitempty"`
	Origin    TypeOrigin        `json:"origin"`
	Vendor    *string           `json:"vendor,omitempty"`
	Rotation  *bool             `json:"rotation,omitempty"`
}

type SecretTypeInput struct {
	Name      string                 `json:"name"`
	Fields    []*SecretFieldDefInput `json:"fields"`
	Heartbeat *bool                  `json:"heartbeat,omitempty"`
	Checkout  *bool                  `json:"checkout,omitempty"`
	Rotation  *bool                  `json:"rotation,omitempty"`
}

type SecretUse struct {
	ID            string   `json:"id"`
	SecretName    string   `json:"secretName"`
	FieldKey      string   `json:"fieldKey"`
	Argv          []string `json:"argv"`
	ClientLabel   string   `json:"clientLabel"`
	State         string   `json:"state"`
	ExpiresAtUnix int      `json:"expiresAtUnix"`
	Reveal        bool     `json:"reveal"`
	RunID         *string  `json:"runId,omitempty"`
	Purpose       string   `json:"purpose"`
	Requester     string   `json:"requester"`
}

type SecretUseOutcome struct {
	ID      string            `json:"id"`
	Decided bool              `json:"decided"`
	Use     *SecretUse        `json:"use,omitempty"`
	Reason  *SecretUseRefusal `json:"reason,omitempty"`
}

type SecretUseRun struct {
	RunID             string       `json:"runId"`
	Uses              []*SecretUse `json:"uses"`
	MfaFreshUntilUnix int          `json:"mfaFreshUntilUnix"`
}

type SecretVersion struct {
	VersionNo        int      `json:"versionNo"`
	CreatedBy        string   `json:"createdBy"`
	CreatedByName    string   `json:"createdByName"`
	CreatedAt        string   `json:"createdAt"`
	Active           bool     `json:"active"`
	FieldKeys        []string `json:"fieldKeys"`
	ChangedFieldKeys []string `json:"changedFieldKeys"`
}

type SecuritySettings struct {
	DefaultPasswordPolicyID        *string `json:"defaultPasswordPolicyId,omitempty"`
	RequireMfaForSensitiveCheckout bool    `json:"requireMfaForSensitiveCheckout"`
	AllowAPIForSensitive           bool    `json:"allowApiForSensitive"`
	RequestHistoryRetentionDays    *int    `json:"requestHistoryRetentionDays,omitempty"`
	SessionTTLSeconds              *int    `json:"sessionTtlSeconds,omitempty"`
	RequireMfaForReveal            bool    `json:"requireMfaForReveal"`
}

type SecuritySettingsInput struct {
	DefaultPasswordPolicyID        *string `json:"defaultPasswordPolicyId,omitempty"`
	RequireMfaForSensitiveCheckout *bool   `json:"requireMfaForSensitiveCheckout,omitempty"`
	AllowAPIForSensitive           *bool   `json:"allowApiForSensitive,omitempty"`
	RequestHistoryRetentionDays    *int    `json:"requestHistoryRetentionDays,omitempty"`
	SessionTTLSeconds              *int    `json:"sessionTtlSeconds,omitempty"`
	RequireMfaForReveal            *bool   `json:"requireMfaForReveal,omitempty"`
}

type ServiceAccount struct {
	ID                string   `json:"id"`
	Name              string   `json:"name"`
	Description       string   `json:"description"`
	Disabled          bool     `json:"disabled"`
	CreatedBy         string   `json:"createdBy"`
	CreatedAtUnix     int      `json:"createdAtUnix"`
	OidcIssuer        *string  `json:"oidcIssuer,omitempty"`
	OidcSubject       *string  `json:"oidcSubject,omitempty"`
	OidcAllowedGroups []string `json:"oidcAllowedGroups"`
}

type SSHSessionTicket struct {
	WsURL            string `json:"wsUrl"`
	Ticket           string `json:"ticket"`
	SessionID        string `json:"sessionId"`
	ExpiresInSeconds int    `json:"expiresInSeconds"`
}

type Subscription struct {
}

type Target struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	Hostname     string   `json:"hostname"`
	Kind         *string  `json:"kind,omitempty"`
	Domain       *string  `json:"domain,omitempty"`
	Realm        *string  `json:"realm,omitempty"`
	ConnectionID string   `json:"connectionId"`
	Description  *string  `json:"description,omitempty"`
	SecretCount  int      `json:"secretCount"`
	OwnerUserID  *string  `json:"ownerUserId,omitempty"`
	SSHHostKeys  []string `json:"sshHostKeys"`
}

type TargetInput struct {
	ID           *string  `json:"id,omitempty"`
	Name         string   `json:"name"`
	Hostname     string   `json:"hostname"`
	Kind         *string  `json:"kind,omitempty"`
	Domain       *string  `json:"domain,omitempty"`
	Realm        *string  `json:"realm,omitempty"`
	ConnectionID string   `json:"connectionId"`
	Description  *string  `json:"description,omitempty"`
	SSHHostKeys  []string `json:"sshHostKeys,omitempty"`
}

type UpdateSecretInput struct {
	Name      *string          `json:"name,omitempty"`
	TargetID  *string          `json:"targetId,omitempty"`
	ExpiresAt *string          `json:"expiresAt,omitempty"`
	Fields    []*KeyValueInput `json:"fields,omitempty"`
	FolderID  *string          `json:"folderId,omitempty"`
}

type UseGrant struct {
	ID            string             `json:"id"`
	TokenID       string             `json:"tokenId"`
	SecretIds     []string           `json:"secretIds"`
	FolderID      *string            `json:"folderId,omitempty"`
	FieldKeys     []string           `json:"fieldKeys"`
	Programs      []*UseGrantProgram `json:"programs"`
	ExpiresAtUnix int                `json:"expiresAtUnix"`
	MaxUses       int                `json:"maxUses"`
	Uses          int                `json:"uses"`
	RevokedAtUnix int                `json:"revokedAtUnix"`
	AllowReveal   bool               `json:"allowReveal"`
}

type UseGrantInput struct {
	TokenID       string                  `json:"tokenId"`
	SecretIds     []string                `json:"secretIds,omitempty"`
	FolderID      *string                 `json:"folderId,omitempty"`
	FieldKeys     []string                `json:"fieldKeys,omitempty"`
	Programs      []*UseGrantProgramInput `json:"programs"`
	ExpiresAtUnix int                     `json:"expiresAtUnix"`
	MaxUses       *int                    `json:"maxUses,omitempty"`
	AllowReveal   *bool                   `json:"allowReveal,omitempty"`
}

type UseGrantProgram struct {
	Program    string `json:"program"`
	ArgPattern string `json:"argPattern"`
}

type UseGrantProgramInput struct {
	Program    string `json:"program"`
	ArgPattern string `json:"argPattern"`
}

type User struct {
	ID            string   `json:"id"`
	Name          string   `json:"name"`
	Username      string   `json:"username"`
	Email         string   `json:"email"`
	Roles         []string `json:"roles"`
	IsRoot        bool     `json:"isRoot"`
	Subject       string   `json:"subject"`
	EmailVerified bool     `json:"emailVerified"`
	Disabled      bool     `json:"disabled"`
}

type UserLabel struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UserToken struct {
	ID             string `json:"id"`
	Label          string `json:"label"`
	ClientName     string `json:"clientName"`
	CreatedAtUnix  int    `json:"createdAtUnix"`
	LastUsedAtUnix int    `json:"lastUsedAtUnix"`
	ExpiresAtUnix  int    `json:"expiresAtUnix"`
	RevokedAtUnix  int    `json:"revokedAtUnix"`
}

type ApprovalStatus string

const (
	ApprovalStatusPending  ApprovalStatus = "pending"
	ApprovalStatusApproved ApprovalStatus = "approved"
	ApprovalStatusDenied   ApprovalStatus = "denied"
)

var AllApprovalStatus = []ApprovalStatus{
	ApprovalStatusPending,
	ApprovalStatusApproved,
	ApprovalStatusDenied,
}

func (e ApprovalStatus) IsValid() bool {
	switch e {
	case ApprovalStatusPending, ApprovalStatusApproved, ApprovalStatusDenied:
		return true
	}
	return false
}

func (e ApprovalStatus) String() string {
	return string(e)
}

func (e *ApprovalStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ApprovalStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ApprovalStatus", str)
	}
	return nil
}

func (e ApprovalStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ApprovalStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ApprovalStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ComponentStatus string

const (
	ComponentStatusOk            ComponentStatus = "OK"
	ComponentStatusUnavailable   ComponentStatus = "UNAVAILABLE"
	ComponentStatusNotConfigured ComponentStatus = "NOT_CONFIGURED"
)

var AllComponentStatus = []ComponentStatus{
	ComponentStatusOk,
	ComponentStatusUnavailable,
	ComponentStatusNotConfigured,
}

func (e ComponentStatus) IsValid() bool {
	switch e {
	case ComponentStatusOk, ComponentStatusUnavailable, ComponentStatusNotConfigured:
		return true
	}
	return false
}

func (e ComponentStatus) String() string {
	return string(e)
}

func (e *ComponentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ComponentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ComponentStatus", str)
	}
	return nil
}

func (e ComponentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ComponentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ComponentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DependencyHealth string

const (
	DependencyHealthOk       DependencyHealth = "OK"
	DependencyHealthDegraded DependencyHealth = "DEGRADED"
	DependencyHealthDown     DependencyHealth = "DOWN"
)

var AllDependencyHealth = []DependencyHealth{
	DependencyHealthOk,
	DependencyHealthDegraded,
	DependencyHealthDown,
}

func (e DependencyHealth) IsValid() bool {
	switch e {
	case DependencyHealthOk, DependencyHealthDegraded, DependencyHealthDown:
		return true
	}
	return false
}

func (e DependencyHealth) String() string {
	return string(e)
}

func (e *DependencyHealth) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DependencyHealth(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DependencyHealth", str)
	}
	return nil
}

func (e DependencyHealth) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DependencyHealth) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DependencyHealth) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FieldKind string

const (
	FieldKindText      FieldKind = "text"
	FieldKindMultiline FieldKind = "multiline"
	FieldKindPassword  FieldKind = "password"
	FieldKindBoolean   FieldKind = "boolean"
	FieldKindSelect    FieldKind = "select"
	FieldKindFile      FieldKind = "file"
	FieldKindSensitive FieldKind = "sensitive"
)

var AllFieldKind = []FieldKind{
	FieldKindText,
	FieldKindMultiline,
	FieldKindPassword,
	FieldKindBoolean,
	FieldKindSelect,
	FieldKindFile,
	FieldKindSensitive,
}

func (e FieldKind) IsValid() bool {
	switch e {
	case FieldKindText, FieldKindMultiline, FieldKindPassword, FieldKindBoolean, FieldKindSelect, FieldKindFile, FieldKindSensitive:
		return true
	}
	return false
}

func (e FieldKind) String() string {
	return string(e)
}

func (e *FieldKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FieldKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FieldKind", str)
	}
	return nil
}

func (e FieldKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FieldKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FieldKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FolderRole string

const (
	FolderRoleRead   FolderRole = "read"
	FolderRoleWrite  FolderRole = "write"
	FolderRoleDelete FolderRole = "delete"
	FolderRoleBulk   FolderRole = "bulk"
	FolderRoleOwner  FolderRole = "owner"
)

var AllFolderRole = []FolderRole{
	FolderRoleRead,
	FolderRoleWrite,
	FolderRoleDelete,
	FolderRoleBulk,
	FolderRoleOwner,
}

func (e FolderRole) IsValid() bool {
	switch e {
	case FolderRoleRead, FolderRoleWrite, FolderRoleDelete, FolderRoleBulk, FolderRoleOwner:
		return true
	}
	return false
}

func (e FolderRole) String() string {
	return string(e)
}

func (e *FolderRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FolderRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FolderRole", str)
	}
	return nil
}

func (e FolderRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FolderRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FolderRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FolderScope string

const (
	FolderScopePersonal FolderScope = "personal"
	FolderScopeGroup    FolderScope = "group"
	FolderScopeRole     FolderScope = "role"
)

var AllFolderScope = []FolderScope{
	FolderScopePersonal,
	FolderScopeGroup,
	FolderScopeRole,
}

func (e FolderScope) IsValid() bool {
	switch e {
	case FolderScopePersonal, FolderScopeGroup, FolderScopeRole:
		return true
	}
	return false
}

func (e FolderScope) String() string {
	return string(e)
}

func (e *FolderScope) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FolderScope(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FolderScope", str)
	}
	return nil
}

func (e FolderScope) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FolderScope) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FolderScope) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type HeartbeatResult string

const (
	HeartbeatResultOk               HeartbeatResult = "ok"
	HeartbeatResultFailed           HeartbeatResult = "failed"
	HeartbeatResultUnreachable      HeartbeatResult = "unreachable"
	HeartbeatResultUnknown          HeartbeatResult = "unknown"
	HeartbeatResultHostKeyNotPinned HeartbeatResult = "hostKeyNotPinned"
	HeartbeatResultHostKeyMismatch  HeartbeatResult = "hostKeyMismatch"
)

var AllHeartbeatResult = []HeartbeatResult{
	HeartbeatResultOk,
	HeartbeatResultFailed,
	HeartbeatResultUnreachable,
	HeartbeatResultUnknown,
	HeartbeatResultHostKeyNotPinned,
	HeartbeatResultHostKeyMismatch,
}

func (e HeartbeatResult) IsValid() bool {
	switch e {
	case HeartbeatResultOk, HeartbeatResultFailed, HeartbeatResultUnreachable, HeartbeatResultUnknown, HeartbeatResultHostKeyNotPinned, HeartbeatResultHostKeyMismatch:
		return true
	}
	return false
}

func (e HeartbeatResult) String() string {
	return string(e)
}

func (e *HeartbeatResult) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HeartbeatResult(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HeartbeatResult", str)
	}
	return nil
}

func (e HeartbeatResult) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *HeartbeatResult) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e HeartbeatResult) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PolicyEnforcement string

const (
	PolicyEnforcementLax    PolicyEnforcement = "lax"
	PolicyEnforcementStrict PolicyEnforcement = "strict"
)

var AllPolicyEnforcement = []PolicyEnforcement{
	PolicyEnforcementLax,
	PolicyEnforcementStrict,
}

func (e PolicyEnforcement) IsValid() bool {
	switch e {
	case PolicyEnforcementLax, PolicyEnforcementStrict:
		return true
	}
	return false
}

func (e PolicyEnforcement) String() string {
	return string(e)
}

func (e *PolicyEnforcement) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PolicyEnforcement(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PolicyEnforcement", str)
	}
	return nil
}

func (e PolicyEnforcement) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PolicyEnforcement) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PolicyEnforcement) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PwStartClass string

const (
	PwStartClassAny    PwStartClass = "any"
	PwStartClassLetter PwStartClass = "letter"
	PwStartClassDigit  PwStartClass = "digit"
	PwStartClassSymbol PwStartClass = "symbol"
)

var AllPwStartClass = []PwStartClass{
	PwStartClassAny,
	PwStartClassLetter,
	PwStartClassDigit,
	PwStartClassSymbol,
}

func (e PwStartClass) IsValid() bool {
	switch e {
	case PwStartClassAny, PwStartClassLetter, PwStartClassDigit, PwStartClassSymbol:
		return true
	}
	return false
}

func (e PwStartClass) String() string {
	return string(e)
}

func (e *PwStartClass) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PwStartClass(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PwStartClass", str)
	}
	return nil
}

func (e PwStartClass) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PwStartClass) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PwStartClass) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RaciAction string

const (
	RaciActionC RaciAction = "C"
	RaciActionI RaciAction = "I"
	RaciActionA RaciAction = "A"
	RaciActionR RaciAction = "R"
)

var AllRaciAction = []RaciAction{
	RaciActionC,
	RaciActionI,
	RaciActionA,
	RaciActionR,
}

func (e RaciAction) IsValid() bool {
	switch e {
	case RaciActionC, RaciActionI, RaciActionA, RaciActionR:
		return true
	}
	return false
}

func (e RaciAction) String() string {
	return string(e)
}

func (e *RaciAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RaciAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RaciAction", str)
	}
	return nil
}

func (e RaciAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RaciAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RaciAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RaciGrant string

const (
	RaciGrantAllow RaciGrant = "allow"
	RaciGrantDeny  RaciGrant = "deny"
)

var AllRaciGrant = []RaciGrant{
	RaciGrantAllow,
	RaciGrantDeny,
}

func (e RaciGrant) IsValid() bool {
	switch e {
	case RaciGrantAllow, RaciGrantDeny:
		return true
	}
	return false
}

func (e RaciGrant) String() string {
	return string(e)
}

func (e *RaciGrant) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RaciGrant(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RaciGrant", str)
	}
	return nil
}

func (e RaciGrant) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RaciGrant) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RaciGrant) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RequestKind string

const (
	RequestKindSecretAccess RequestKind = "secret_access"
	RequestKindFolderMove   RequestKind = "folder_move"
	RequestKindSecretMove   RequestKind = "secret_move"
)

var AllRequestKind = []RequestKind{
	RequestKindSecretAccess,
	RequestKindFolderMove,
	RequestKindSecretMove,
}

func (e RequestKind) IsValid() bool {
	switch e {
	case RequestKindSecretAccess, RequestKindFolderMove, RequestKindSecretMove:
		return true
	}
	return false
}

func (e RequestKind) String() string {
	return string(e)
}

func (e *RequestKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RequestKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RequestKind", str)
	}
	return nil
}

func (e RequestKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RequestKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RequestKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RotationState string

const (
	RotationStateOk       RotationState = "ok"
	RotationStateFailed   RotationState = "failed"
	RotationStateDegraded RotationState = "degraded"
	RotationStateRotating RotationState = "rotating"
	RotationStateUnknown  RotationState = "unknown"
)

var AllRotationState = []RotationState{
	RotationStateOk,
	RotationStateFailed,
	RotationStateDegraded,
	RotationStateRotating,
	RotationStateUnknown,
}

func (e RotationState) IsValid() bool {
	switch e {
	case RotationStateOk, RotationStateFailed, RotationStateDegraded, RotationStateRotating, RotationStateUnknown:
		return true
	}
	return false
}

func (e RotationState) String() string {
	return string(e)
}

func (e *RotationState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RotationState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RotationState", str)
	}
	return nil
}

func (e RotationState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RotationState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RotationState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SecretUseDecision string

const (
	SecretUseDecisionApprove SecretUseDecision = "APPROVE"
	SecretUseDecisionDeny    SecretUseDecision = "DENY"
)

var AllSecretUseDecision = []SecretUseDecision{
	SecretUseDecisionApprove,
	SecretUseDecisionDeny,
}

func (e SecretUseDecision) IsValid() bool {
	switch e {
	case SecretUseDecisionApprove, SecretUseDecisionDeny:
		return true
	}
	return false
}

func (e SecretUseDecision) String() string {
	return string(e)
}

func (e *SecretUseDecision) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SecretUseDecision(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SecretUseDecision", str)
	}
	return nil
}

func (e SecretUseDecision) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SecretUseDecision) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SecretUseDecision) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SecretUseRefusal string

const (
	SecretUseRefusalExpired        SecretUseRefusal = "EXPIRED"
	SecretUseRefusalAlreadyDecided SecretUseRefusal = "ALREADY_DECIDED"
	SecretUseRefusalNotFound       SecretUseRefusal = "NOT_FOUND"
	SecretUseRefusalNotPermitted   SecretUseRefusal = "NOT_PERMITTED"
	SecretUseRefusalUnavailable    SecretUseRefusal = "UNAVAILABLE"
)

var AllSecretUseRefusal = []SecretUseRefusal{
	SecretUseRefusalExpired,
	SecretUseRefusalAlreadyDecided,
	SecretUseRefusalNotFound,
	SecretUseRefusalNotPermitted,
	SecretUseRefusalUnavailable,
}

func (e SecretUseRefusal) IsValid() bool {
	switch e {
	case SecretUseRefusalExpired, SecretUseRefusalAlreadyDecided, SecretUseRefusalNotFound, SecretUseRefusalNotPermitted, SecretUseRefusalUnavailable:
		return true
	}
	return false
}

func (e SecretUseRefusal) String() string {
	return string(e)
}

func (e *SecretUseRefusal) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SecretUseRefusal(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SecretUseRefusal", str)
	}
	return nil
}

func (e SecretUseRefusal) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SecretUseRefusal) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SecretUseRefusal) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type StepUpMode string

const (
	StepUpModeInherit StepUpMode = "inherit"
	StepUpModeRequire StepUpMode = "require"
	StepUpModeOff     StepUpMode = "off"
)

var AllStepUpMode = []StepUpMode{
	StepUpModeInherit,
	StepUpModeRequire,
	StepUpModeOff,
}

func (e StepUpMode) IsValid() bool {
	switch e {
	case StepUpModeInherit, StepUpModeRequire, StepUpModeOff:
		return true
	}
	return false
}

func (e StepUpMode) String() string {
	return string(e)
}

func (e *StepUpMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = StepUpMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid StepUpMode", str)
	}
	return nil
}

func (e StepUpMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *StepUpMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e StepUpMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SubjectKind string

const (
	SubjectKindGroup    SubjectKind = "group"
	SubjectKindUser     SubjectKind = "user"
	SubjectKindEveryone SubjectKind = "everyone"
)

var AllSubjectKind = []SubjectKind{
	SubjectKindGroup,
	SubjectKindUser,
	SubjectKindEveryone,
}

func (e SubjectKind) IsValid() bool {
	switch e {
	case SubjectKindGroup, SubjectKindUser, SubjectKindEveryone:
		return true
	}
	return false
}

func (e SubjectKind) String() string {
	return string(e)
}

func (e *SubjectKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SubjectKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SubjectKind", str)
	}
	return nil
}

func (e SubjectKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SubjectKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SubjectKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TypeOrigin string

const (
	TypeOriginSystem    TypeOrigin = "system"
	TypeOriginExtension TypeOrigin = "extension"
	TypeOriginCustom    TypeOrigin = "custom"
)

var AllTypeOrigin = []TypeOrigin{
	TypeOriginSystem,
	TypeOriginExtension,
	TypeOriginCustom,
}

func (e TypeOrigin) IsValid() bool {
	switch e {
	case TypeOriginSystem, TypeOriginExtension, TypeOriginCustom:
		return true
	}
	return false
}

func (e TypeOrigin) String() string {
	return string(e)
}

func (e *TypeOrigin) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TypeOrigin(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TypeOrigin", str)
	}
	return nil
}

func (e TypeOrigin) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TypeOrigin) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TypeOrigin) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
