package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"time"

	identityv1 "github.com/Sneakers-PAM/sneakers-gateway/gen/go/thirdparty/identity/v1"
	notifyv1 "github.com/Sneakers-PAM/sneakers-gateway/gen/go/thirdparty/notify/v1"
	sshbrokerv1 "github.com/Sneakers-PAM/sneakers-gateway/gen/go/thirdparty/sshbroker/v1"
	vaultv1 "github.com/Sneakers-PAM/sneakers-gateway/gen/go/thirdparty/vault/v1"
	workflowv1 "github.com/Sneakers-PAM/sneakers-gateway/gen/go/thirdparty/workflow/v1"
	"github.com/Sneakers-PAM/sneakers-gateway/internal/safeconv"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// SaveConnection is the resolver for the saveConnection field.
func (r *mutationResolver) SaveConnection(ctx context.Context, input ConnectionInput) (*Connection, error) {
	resp, err := r.Vault.SaveConnection(ctx, &vaultv1.SaveConnectionRequest{Actor: actorOf(ctx), Connection: protoConnInput(input)})
	if err != nil {
		return nil, err
	}
	return gqlConnection(resp.GetConnection()), nil
}

// DeleteConnection is the resolver for the deleteConnection field.
func (r *mutationResolver) DeleteConnection(ctx context.Context, id string) (bool, error) {
	resp, err := r.Vault.DeleteConnection(ctx, &vaultv1.DeleteConnectionRequest{Actor: actorOf(ctx), Id: id})
	if err != nil {
		return false, err
	}
	return resp.GetRemoved(), nil
}

// SaveTarget is the resolver for the saveTarget field.
func (r *mutationResolver) SaveTarget(ctx context.Context, input TargetInput) (*Target, error) {
	t := protoTargetInput(input)
	keys, err := HostKeysForSave(ctx, r.Vault, actorOf(ctx), t.GetId(), input.SSHHostKeys)
	if err != nil {
		return nil, err
	}
	t.SshHostKeys = keys
	resp, err := r.Vault.SaveTarget(ctx, &vaultv1.SaveTargetRequest{Actor: actorOf(ctx), Target: t})
	if err != nil {
		return nil, err
	}
	return gqlTarget(resp.GetTarget()), nil
}

// DeleteTarget is the resolver for the deleteTarget field.
func (r *mutationResolver) DeleteTarget(ctx context.Context, id string) (bool, error) {
	resp, err := r.Vault.DeleteTarget(ctx, &vaultv1.DeleteTargetRequest{Actor: actorOf(ctx), Id: id})
	if err != nil {
		return false, err
	}
	return resp.GetRemoved(), nil
}

// SavePasswordPolicy is the resolver for the savePasswordPolicy field.
func (r *mutationResolver) SavePasswordPolicy(ctx context.Context, input PasswordPolicyInput) (*PasswordPolicy, error) {
	resp, err := r.Vault.SavePasswordPolicy(ctx, &vaultv1.SavePasswordPolicyRequest{Actor: actorOf(ctx), Policy: protoPolicyInput(input)})
	if err != nil {
		return nil, err
	}
	return gqlPolicy(resp.GetPolicy()), nil
}

// DeletePasswordPolicy is the resolver for the deletePasswordPolicy field.
func (r *mutationResolver) DeletePasswordPolicy(ctx context.Context, id string) (bool, error) {
	resp, err := r.Vault.DeletePasswordPolicy(ctx, &vaultv1.DeletePasswordPolicyRequest{Actor: actorOf(ctx), Id: id})
	if err != nil {
		return false, err
	}
	return resp.GetRemoved(), nil
}

// UpdateSecuritySettings is the resolver for the updateSecuritySettings field.
func (r *mutationResolver) UpdateSecuritySettings(ctx context.Context, input SecuritySettingsInput) (*SecuritySettings, error) {
	req := &vaultv1.UpdateSecuritySettingsRequest{Actor: actorOf(ctx)}
	req.DefaultPasswordPolicyId = input.DefaultPasswordPolicyID
	req.RequireMfaForSensitiveCheckout = input.RequireMfaForSensitiveCheckout
	req.AllowApiForSensitive = input.AllowAPIForSensitive
	req.RequestHistoryRetentionDays = intToI32Ptr(input.RequestHistoryRetentionDays)
	req.SessionTtlSeconds = intToI32Ptr(input.SessionTTLSeconds)
	req.RequireMfaForReveal = input.RequireMfaForReveal
	resp, err := r.Vault.UpdateSecuritySettings(ctx, req)
	if err != nil {
		return nil, err
	}
	return gqlSettings(resp.GetSettings()), nil
}

// CreateSecretType is the resolver for the createSecretType field.
func (r *mutationResolver) CreateSecretType(ctx context.Context, input SecretTypeInput) (*SecretType, error) {
	resp, err := r.Vault.CreateSecretType(ctx, &vaultv1.CreateSecretTypeRequest{Actor: actorOf(ctx), Type: protoTypeInput(input)})
	if err != nil {
		return nil, err
	}
	return gqlType(resp.GetType()), nil
}

// UpdateSecretType is the resolver for the updateSecretType field.
func (r *mutationResolver) UpdateSecretType(ctx context.Context, id string, input SecretTypeInput) (*SecretType, error) {
	resp, err := r.Vault.UpdateSecretType(ctx, &vaultv1.UpdateSecretTypeRequest{Actor: actorOf(ctx), Id: id, Type: protoTypeInput(input)})
	if err != nil {
		return nil, err
	}
	return gqlType(resp.GetType()), nil
}

// DeleteSecretType is the resolver for the deleteSecretType field.
func (r *mutationResolver) DeleteSecretType(ctx context.Context, id string) (bool, error) {
	resp, err := r.Vault.DeleteSecretType(ctx, &vaultv1.DeleteSecretTypeRequest{Actor: actorOf(ctx), Id: id})
	if err != nil {
		return false, err
	}
	return resp.GetRemoved(), nil
}

// CloneSecretType is the resolver for the cloneSecretType field.
func (r *mutationResolver) CloneSecretType(ctx context.Context, id string) (*SecretType, error) {
	resp, err := r.Vault.CloneSecretType(ctx, &vaultv1.CloneSecretTypeRequest{Actor: actorOf(ctx), Id: id})
	if err != nil {
		return nil, err
	}
	return gqlType(resp.GetType()), nil
}

// ImportExtension is the resolver for the importExtension field.
func (r *mutationResolver) ImportExtension(ctx context.Context, id string) (*SecretType, error) {
	resp, err := r.Vault.ImportExtension(ctx, &vaultv1.ImportExtensionRequest{Actor: actorOf(ctx), Id: id})
	if err != nil {
		return nil, err
	}
	return gqlType(resp.GetType()), nil
}

// ImportExtensionFromJSON is the resolver for the importExtensionFromJson field.
func (r *mutationResolver) ImportExtensionFromJSON(ctx context.Context, json string) (*SecretType, error) {
	resp, err := r.Vault.ImportExtensionFromJson(ctx, &vaultv1.ImportExtensionFromJsonRequest{Actor: actorOf(ctx), Json: json})
	if err != nil {
		return nil, err
	}
	return gqlType(resp.GetType()), nil
}

// CreateSecret is the resolver for the createSecret field.
func (r *mutationResolver) CreateSecret(ctx context.Context, input CreateSecretInput) (*Secret, error) {
	fields := make(map[string]string, len(input.Fields))
	for _, kv := range input.Fields {
		fields[kv.Key] = kv.Value
	}
	resp, err := r.Vault.CreateSecret(ctx, &vaultv1.CreateSecretRequest{
		Actor: actorOf(ctx), Name: input.Name, FolderId: input.FolderID, TypeId: input.TypeID,
		TargetId: deref(input.TargetID), ExpiresAt: deref(input.ExpiresAt), Fields: fields,
	})
	if err != nil {
		return nil, err
	}
	return gqlSecret(resp.GetSecret()), nil
}

// UpdateSecret is the resolver for the updateSecret field.
func (r *mutationResolver) UpdateSecret(ctx context.Context, id string, input UpdateSecretInput) (*Secret, error) {
	fields := map[string]string{}
	for _, kv := range input.Fields {
		fields[kv.Key] = kv.Value
	}
	resp, err := r.Vault.UpdateSecret(ctx, &vaultv1.UpdateSecretRequest{
		Actor: actorOf(ctx), Id: id, Name: deref(input.Name),
		TargetId: deref(input.TargetID), ExpiresAt: deref(input.ExpiresAt), Fields: fields,
		DestFolderId: deref(input.FolderID),
	})
	if err != nil {
		return nil, err
	}
	return gqlSecret(resp.GetSecret()), nil
}

// RevealSecretField is the resolver for the revealSecretField field.
func (r *mutationResolver) RevealSecretField(ctx context.Context, id string, fieldKey string) (string, error) {
	resp, err := r.Vault.RevealSecretField(ctx, &vaultv1.RevealSecretFieldRequest{Actor: actorOf(ctx), Id: id, FieldKey: fieldKey})
	if err != nil {
		return "", err
	}
	return resp.GetValue(), nil
}

// RevealSecretVersionField is the resolver for the revealSecretVersionField field.
func (r *mutationResolver) RevealSecretVersionField(ctx context.Context, secretID string, versionNo int, fieldKey string) (string, error) {
	resp, err := r.Vault.RevealSecretVersionField(ctx, &vaultv1.RevealSecretVersionFieldRequest{
		Actor: actorOf(ctx), SecretId: secretID, VersionNo: safeconv.Int32(versionNo), FieldKey: fieldKey,
	})
	if err != nil {
		return "", err
	}
	return resp.GetValue(), nil
}

// RestoreSecretVersion is the resolver for the restoreSecretVersion field.
func (r *mutationResolver) RestoreSecretVersion(ctx context.Context, secretID string, versionNo int) (*Secret, error) {
	if err := r.refuseWhileCheckedOut(ctx, secretID, "restore a version"); err != nil {
		return nil, err
	}
	resp, err := r.Vault.RestoreSecretVersion(ctx, &vaultv1.RestoreSecretVersionRequest{
		Actor: actorOf(ctx), SecretId: secretID, VersionNo: safeconv.Int32(versionNo),
	})
	if err != nil {
		return nil, err
	}
	return gqlSecret(resp.GetSecret()), nil
}

// BreakGlassSecret is the resolver for the breakGlassSecret field: a TOTP MFA
// step-up in front of the vault's emergency-access reveal. The vault call is
// only made once the acting user's current code has been verified against
// their confirmed factor; a missing/invalid code never reaches the vault.
func (r *mutationResolver) BreakGlassSecret(ctx context.Context, secretID string, reason string, code string) ([]*KeyValue, error) {
	actor := actorOf(ctx)
	vr, err := r.Identity.VerifyTotp(ctx, &identityv1.VerifyTotpRequest{UserId: actor.GetUserId(), Code: code})
	if err != nil {
		return nil, err
	}
	if !vr.GetOk() {
		return nil, fmt.Errorf("invalid or missing MFA code")
	}
	resp, err := r.Vault.BreakGlassSecret(ctx, &vaultv1.BreakGlassSecretRequest{Actor: actor, SecretId: secretID, Reason: reason})
	if err != nil {
		return nil, err
	}
	out := make([]*KeyValue, 0, len(resp.GetFields()))
	for k, v := range resp.GetFields() {
		out = append(out, &KeyValue{Key: k, Value: v})
	}
	return out, nil
}

// CopySecret is the resolver for the copySecret field.
func (r *mutationResolver) CopySecret(ctx context.Context, id string) (*string, error) {
	resp, err := r.Vault.CopySecret(ctx, &vaultv1.CopySecretRequest{Actor: actorOf(ctx), Id: id})
	if err != nil {
		return nil, err
	}
	return strPtr(resp.GetValue()), nil
}

// RetireSecret is the resolver for the retireSecret field.
func (r *mutationResolver) RetireSecret(ctx context.Context, id string) (*Secret, error) {
	resp, err := r.Vault.RetireSecret(ctx, &vaultv1.RetireSecretRequest{Actor: actorOf(ctx), Id: id})
	if err != nil {
		return nil, err
	}
	return gqlSecret(resp.GetSecret()), nil
}

// RestoreSecret is the resolver for the restoreSecret field.
func (r *mutationResolver) RestoreSecret(ctx context.Context, id string) (*Secret, error) {
	resp, err := r.Vault.RestoreSecret(ctx, &vaultv1.RestoreSecretRequest{Actor: actorOf(ctx), Id: id})
	if err != nil {
		return nil, err
	}
	return gqlSecret(resp.GetSecret()), nil
}

// DeleteSecret is the resolver for the deleteSecret field.
func (r *mutationResolver) DeleteSecret(ctx context.Context, id string) (bool, error) {
	if _, err := r.Vault.DeleteSecret(ctx, &vaultv1.DeleteSecretRequest{Actor: actorOf(ctx), Id: id}); err != nil {
		return false, err
	}
	return true, nil
}

// ImportCertificate is the resolver for the importCertificate field: it
// decodes the uploaded file and hands it to the vault's certificate importer.
// A multi-entry container (e.g. a PKCS12/JKS bundle with several cert+key
// pairs) with no alias given comes back with Aliases populated and Secret/Meta
// nil and NO gRPC error — that's a normal result, not a failure, so it's
// passed straight through rather than treated as an error.
func (r *mutationResolver) ImportCertificate(ctx context.Context, folderID string, name string, fileBase64 string, passphrase *string, alias *string) (*ImportCertificateResult, error) {
	fileBytes, err := base64.StdEncoding.DecodeString(fileBase64)
	if err != nil {
		return nil, status.Error(codes.InvalidArgument, "fileBase64 is not valid base64")
	}
	resp, err := r.Vault.ImportCertificate(ctx, &vaultv1.ImportCertificateRequest{
		Actor: actorOf(ctx), FolderId: folderID, Name: name, FileBytes: fileBytes,
		Passphrase: deref(passphrase), Alias: deref(alias),
	})
	if err != nil {
		return nil, err
	}
	out := &ImportCertificateResult{Aliases: resp.GetAliases()}
	if resp.GetSecret() != nil {
		out.Secret = gqlSecret(resp.GetSecret())
	}
	if resp.GetMeta() != nil {
		out.Meta = gqlCertMeta(resp.GetMeta())
	}
	return out, nil
}

// ExportCertificate is the resolver for the exportCertificate field: it fetches
// the exported container/key bytes from the vault and base64-encodes them for
// the GraphQL transport (the browser then decodes + downloads them).
func (r *mutationResolver) ExportCertificate(ctx context.Context, secretID string, format string, newPassphrase *string) (*CertExport, error) {
	resp, err := r.Vault.ExportCertificate(ctx, &vaultv1.ExportCertificateRequest{
		Actor: actorOf(ctx), SecretId: secretID, Format: format, NewPassphrase: deref(newPassphrase),
	})
	if err != nil {
		return nil, err
	}
	return &CertExport{
		FileBase64:  base64.StdEncoding.EncodeToString(resp.GetFileBytes()),
		Filename:    resp.GetFilename(),
		ContentType: resp.GetContentType(),
	}, nil
}

// ReplaceCertificate is the resolver for the replaceCertificate field: it
// decodes the uploaded file and hands it to the vault to replace an existing
// certificate secret's material in place. A multi-entry container (e.g. a
// PKCS12/JKS bundle with several cert+key pairs) with no alias given comes
// back with Aliases populated and Secret/Meta nil and NO gRPC error — that's
// a normal result, not a failure, so it's passed straight through rather
// than treated as an error.
func (r *mutationResolver) ReplaceCertificate(ctx context.Context, secretID string, fileBase64 string, passphrase *string, alias *string) (*ImportCertificateResult, error) {
	fileBytes, err := base64.StdEncoding.DecodeString(fileBase64)
	if err != nil {
		return nil, status.Error(codes.InvalidArgument, "fileBase64 is not valid base64")
	}
	resp, err := r.Vault.ReplaceCertificate(ctx, &vaultv1.ReplaceCertificateRequest{
		Actor: actorOf(ctx), SecretId: secretID, FileBytes: fileBytes,
		Passphrase: deref(passphrase), Alias: deref(alias),
	})
	if err != nil {
		return nil, err
	}
	out := &ImportCertificateResult{Aliases: resp.GetAliases()}
	if resp.GetSecret() != nil {
		out.Secret = gqlSecret(resp.GetSecret())
	}
	if resp.GetMeta() != nil {
		out.Meta = gqlCertMeta(resp.GetMeta())
	}
	return out, nil
}

// GenerateKeyPair is the resolver for the generateKeyPair field.
func (r *mutationResolver) GenerateKeyPair(ctx context.Context, format string) (*KeyPair, error) {
	resp, err := r.Vault.GenerateKeyPair(ctx, &vaultv1.GenerateKeyPairRequest{Actor: actorOf(ctx), Format: format})
	if err != nil {
		return nil, err
	}
	return &KeyPair{PrivateKey: resp.GetPrivateKey(), PublicKey: resp.GetPublicKey()}, nil
}

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, parentID *string, name string) (*Folder, error) {
	resp, err := r.Vault.CreateFolder(ctx, &vaultv1.CreateFolderRequest{Actor: actorOf(ctx), ParentId: deref(parentID), Name: name})
	if err != nil {
		return nil, err
	}
	return gqlFolder(resp.GetFolder()), nil
}

// RenameFolder is the resolver for the renameFolder field.
func (r *mutationResolver) RenameFolder(ctx context.Context, id string, name string) (*Folder, error) {
	resp, err := r.Vault.RenameFolder(ctx, &vaultv1.RenameFolderRequest{Actor: actorOf(ctx), Id: id, Name: name})
	if err != nil {
		return nil, err
	}
	return gqlFolder(resp.GetFolder()), nil
}

// MoveFolder is the resolver for the moveFolder field.
func (r *mutationResolver) MoveFolder(ctx context.Context, id string, newParentID *string) (*Folder, error) {
	resp, err := r.Vault.MoveFolder(ctx, &vaultv1.MoveFolderRequest{Actor: actorOf(ctx), Id: id, NewParentId: deref(newParentID)})
	if err != nil {
		return nil, err
	}
	return gqlFolder(resp.GetFolder()), nil
}

// DeleteFolder is the resolver for the deleteFolder field.
func (r *mutationResolver) DeleteFolder(ctx context.Context, id string, reassignToID *string) (bool, error) {
	if _, err := r.Vault.DeleteFolder(ctx, &vaultv1.DeleteFolderRequest{Actor: actorOf(ctx), Id: id, ReassignToId: deref(reassignToID)}); err != nil {
		return false, err
	}
	return true, nil
}

// ReorderFolders is the resolver for the reorderFolders field.
func (r *mutationResolver) ReorderFolders(ctx context.Context, parentID *string, orderedIds []string) (bool, error) {
	if _, err := r.Vault.ReorderFolders(ctx, &vaultv1.ReorderFoldersRequest{Actor: actorOf(ctx), ParentId: deref(parentID), OrderedIds: orderedIds}); err != nil {
		return false, err
	}
	return true, nil
}

// AddFolderRule is the resolver for the addFolderRule field.
func (r *mutationResolver) AddFolderRule(ctx context.Context, folderID string, subjectKind SubjectKind, subjectID string, role FolderRole) (*FolderAccessRule, error) {
	resp, err := r.Vault.AddFolderRule(ctx, &vaultv1.AddFolderRuleRequest{
		Actor: actorOf(ctx),
		Rule: &vaultv1.FolderAccessRule{
			FolderId: folderID, SubjectKind: subjectKindProto(subjectKind), SubjectId: subjectID, Role: roleProto(role),
		},
	})
	if err != nil {
		return nil, err
	}
	return gqlRule(resp.GetRule()), nil
}

// RemoveFolderRule is the resolver for the removeFolderRule field.
func (r *mutationResolver) RemoveFolderRule(ctx context.Context, id string) (bool, error) {
	if _, err := r.Vault.RemoveFolderRule(ctx, &vaultv1.RemoveFolderRuleRequest{Actor: actorOf(ctx), Id: id}); err != nil {
		return false, err
	}
	return true, nil
}

// SetFolderRuleset is the resolver for the setFolderRuleset field: it replaces a
// folder's owners + ordered firewall-RACI ruleset, then returns the freshly
// persisted ruleset (owners + own rules + inherited).
func (r *mutationResolver) SetFolderRuleset(ctx context.Context, folderID string, owners []string, rules []*RaciRuleInput) (*FolderRuleset, error) {
	protoRules := make([]*vaultv1.RaciRule, 0, len(rules))
	for _, in := range rules {
		protoRules = append(protoRules, protoRaciRuleInput(in))
	}
	if _, err := r.Vault.SetFolderRuleset(ctx, &vaultv1.SetFolderRulesetRequest{
		Actor: actorOf(ctx), FolderId: folderID, Owners: owners, Rules: protoRules,
	}); err != nil {
		return nil, err
	}
	return r.buildFolderRuleset(ctx, folderID)
}

// SetFolderRevealStepUp is the resolver for the setFolderRevealStepUp field.
func (r *mutationResolver) SetFolderRevealStepUp(ctx context.Context, folderID string, mode StepUpMode) (*Folder, error) {
	resp, err := r.Vault.SetFolderRevealStepUp(ctx, &vaultv1.SetFolderRevealStepUpRequest{
		Actor: actorOf(ctx), FolderId: folderID, Mode: stepUpModeProto(mode),
	})
	if err != nil {
		return nil, err
	}
	return gqlFolder(resp.GetFolder()), nil
}

// SetSecretRuleset is the resolver for the setSecretRuleset field: it replaces a
// secret's ordered firewall-RACI ruleset, then returns the freshly persisted
// ruleset (own rules + inherited from the secret's folder chain).
func (r *mutationResolver) SetSecretRuleset(ctx context.Context, secretID string, rules []*RaciRuleInput) (*SecretRuleset, error) {
	protoRules := make([]*vaultv1.RaciRule, 0, len(rules))
	for _, in := range rules {
		protoRules = append(protoRules, protoRaciRuleInput(in))
	}
	if _, err := r.Vault.SetSecretRuleset(ctx, &vaultv1.SetSecretRulesetRequest{
		Actor: actorOf(ctx), SecretId: secretID, Rules: protoRules,
	}); err != nil {
		return nil, err
	}
	return r.buildSecretRuleset(ctx, secretID)
}

// CheckoutSecret is the resolver for the checkoutSecret field.
func (r *mutationResolver) CheckoutSecret(ctx context.Context, secretID string, hours *int) (*Lease, error) {
	resp, err := r.Workflow.CheckoutSecret(ctx, &workflowv1.CheckoutSecretRequest{
		Actor: workflowActorOf(ctx), SecretId: secretID, Hours: int32(ideref(hours)),
	})
	if err != nil {
		return nil, err
	}
	return gqlLease(resp.GetLease()), nil
}

// CheckinSecret is the resolver for the checkinSecret field.
func (r *mutationResolver) CheckinSecret(ctx context.Context, secretID string) (bool, error) {
	if _, err := r.Workflow.CheckinSecret(ctx, &workflowv1.CheckinSecretRequest{Actor: workflowActorOf(ctx), SecretId: secretID}); err != nil {
		return false, err
	}
	return true, nil
}

// CreateAccessRequest is the resolver for the createAccessRequest field.
func (r *mutationResolver) CreateAccessRequest(ctx context.Context, secretID string, reason *string) (*ApprovalRequest, error) {
	req := &workflowv1.CreateAccessRequestRequest{Actor: workflowActorOf(ctx), SecretId: secretID}
	if reason != nil {
		req.Reason = *reason
	}
	resp, err := r.Workflow.CreateAccessRequest(ctx, req)
	if err != nil {
		return nil, err
	}
	return gqlApproval(resp.GetRequest()), nil
}

// CreateFolderMoveRequest is the resolver for the createFolderMoveRequest field:
// a non-admin's request to move a folder shared -> personal, for site-admin
// approval. The move itself is performed by ResolveApproval on approve.
func (r *mutationResolver) CreateFolderMoveRequest(ctx context.Context, folderID string, destParentID string, reason *string, folderName *string, destParentName *string) (*ApprovalRequest, error) {
	req := &workflowv1.CreateFolderMoveRequestRequest{
		Actor: workflowActorOf(ctx), FolderId: folderID, DestParentId: destParentID,
	}
	if reason != nil {
		req.Reason = *reason
	}
	if folderName != nil {
		req.FolderName = *folderName
	}
	if destParentName != nil {
		req.DestParentName = *destParentName
	}
	resp, err := r.Workflow.CreateFolderMoveRequest(ctx, req)
	if err != nil {
		return nil, err
	}
	out := gqlApproval(resp.GetRequest())
	r.enrichApprovalNames(ctx, []*ApprovalRequest{out})
	return out, nil
}

// CreateSecretMoveRequest is the resolver for the createSecretMoveRequest field:
// a non-admin's request to move a secret shared -> personal, for site-admin
// approval. ResolveApproval performs the move on approve.
func (r *mutationResolver) CreateSecretMoveRequest(ctx context.Context, secretID string, destFolderID string, reason *string, secretName *string, destFolderName *string) (*ApprovalRequest, error) {
	req := &workflowv1.CreateSecretMoveRequestRequest{
		Actor: workflowActorOf(ctx), SecretId: secretID, DestFolderId: destFolderID,
	}
	if reason != nil {
		req.Reason = *reason
	}
	if secretName != nil {
		req.SecretName = *secretName
	}
	if destFolderName != nil {
		req.DestFolderName = *destFolderName
	}
	resp, err := r.Workflow.CreateSecretMoveRequest(ctx, req)
	if err != nil {
		return nil, err
	}
	out := gqlApproval(resp.GetRequest())
	r.enrichApprovalNames(ctx, []*ApprovalRequest{out})
	return out, nil
}

// ResolveApproval is the resolver for the resolveApproval field. On approve the
// workflow issues a time-boxed lease for the requester (grantHours clamped
// server-side); grantHours nil/zero uses the workflow's default window.
func (r *mutationResolver) ResolveApproval(ctx context.Context, id string, approve bool, grantHours *int) (*ApprovalRequest, error) {
	req := &workflowv1.ResolveApprovalRequest{Actor: workflowActorOf(ctx), Id: id, Approve: approve}
	if grantHours != nil {
		h := safeconv.Int32(*grantHours)
		req.GrantHours = &h
	}
	resp, err := r.Workflow.ResolveApproval(ctx, req)
	if err != nil {
		return nil, err
	}
	out := gqlApproval(resp.GetRequest())
	r.enrichApprovalNames(ctx, []*ApprovalRequest{out})
	return out, nil
}

// AddApprovalComment is the resolver for the addApprovalComment field. It
// appends a message to an access request's discussion thread and returns the
// updated request with its full thread (author names resolved).
func (r *mutationResolver) AddApprovalComment(ctx context.Context, requestID string, body string) (*ApprovalRequest, error) {
	resp, err := r.Workflow.AddApprovalComment(ctx, &workflowv1.AddApprovalCommentRequest{
		Actor: workflowActorOf(ctx), RequestId: requestID, Body: body,
	})
	if err != nil {
		return nil, err
	}
	out := gqlApproval(resp.GetRequest())
	r.enrichApprovalNames(ctx, []*ApprovalRequest{out})
	return out, nil
}

// RotateSecret is the resolver for the rotateSecret field. Manual rotation
// calls the vault directly (not the workflow) so the full RACI actor context
// is used for firewall enforcement.
func (r *mutationResolver) RotateSecret(ctx context.Context, secretID string) (bool, error) {
	// A manual rotation must not run while the secret is checked out — it would
	// invalidate the credential the active holder is using. (System rotate-on-
	// check-in and break-glass forced rotation are separate paths.)
	if err := r.refuseWhileCheckedOut(ctx, secretID, "rotate"); err != nil {
		return false, err
	}
	if _, err := r.Vault.EnqueueRotation(ctx, &vaultv1.EnqueueRotationRequest{
		Actor: actorOf(ctx), SecretId: secretID, Reason: "manual",
	}); err != nil {
		return false, err
	}
	return true, nil
}

// SetSecretAutomation is the resolver for the setSecretAutomation field.
func (r *mutationResolver) SetSecretAutomation(ctx context.Context, secretID string, disableRotation bool, disableHeartbeat bool) (*Secret, error) {
	resp, err := r.Vault.SetSecretAutomation(ctx, &vaultv1.SetSecretAutomationRequest{
		Actor: actorOf(ctx), SecretId: secretID,
		DisableRotation: disableRotation, DisableHeartbeat: disableHeartbeat,
	})
	if err != nil {
		return nil, err
	}
	return gqlSecret(resp.GetSecret()), nil
}

// SetSecretTokenApproval is the resolver for the setSecretTokenApproval field.
func (r *mutationResolver) SetSecretTokenApproval(ctx context.Context, secretID string, required bool) (*Secret, error) {
	resp, err := r.Vault.SetSecretTokenApproval(ctx, &vaultv1.SetSecretTokenApprovalRequest{Actor: actorOf(ctx), SecretId: secretID, Required: required})
	if err != nil {
		return nil, err
	}
	return gqlSecret(resp.GetSecret()), nil
}

// AddGroupMember is the resolver for the addGroupMember field. Admin-gated:
// only a site-admin or root may edit group membership.
func (r *mutationResolver) AddGroupMember(ctx context.Context, userID string, groupID string) (bool, error) {
	if err := requireAdmin(ctx); err != nil {
		return false, err
	}
	if _, err := r.Identity.AddGroupMember(ctx, &identityv1.AddGroupMemberRequest{UserId: userID, GroupId: groupID, ActingUserId: actorFrom(ctx)}); err != nil {
		return false, err
	}
	return true, nil
}

// RemoveGroupMember is the resolver for the removeGroupMember field. Admin-gated:
// only a site-admin or root may edit group membership.
func (r *mutationResolver) RemoveGroupMember(ctx context.Context, userID string, groupID string) (bool, error) {
	if err := requireAdmin(ctx); err != nil {
		return false, err
	}
	if _, err := r.Identity.RemoveGroupMember(ctx, &identityv1.RemoveGroupMemberRequest{UserId: userID, GroupId: groupID, ActingUserId: actorFrom(ctx)}); err != nil {
		return false, err
	}
	return true, nil
}

// CreateGroup is the resolver for the createGroup field. Admin-gated: only a
// site-admin or root may create a directory group.
func (r *mutationResolver) CreateGroup(ctx context.Context, name string) (*Group, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	resp, err := r.Identity.CreateGroup(ctx, &identityv1.CreateGroupRequest{Name: name, ActingUserId: actorFrom(ctx)})
	if err != nil {
		return nil, err
	}
	g := resp.GetGroup()
	return &Group{ID: g.GetId(), Name: g.GetName()}, nil
}

// CreateLocalUser is the resolver for the createLocalUser field.
func (r *mutationResolver) CreateLocalUser(ctx context.Context, username string, email string, name string, password string) (*User, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	resp, err := r.Identity.CreateLocalUser(ctx, &identityv1.CreateLocalUserRequest{
		Username:     username,
		Email:        email,
		Name:         name,
		Password:     password,
		ActingUserId: actorFrom(ctx),
	})
	if err != nil {
		return nil, err
	}
	return gqlUser(resp.GetUser()), nil
}

// RequestEmailVerification is the resolver for the requestEmailVerification field.
func (r *mutationResolver) RequestEmailVerification(ctx context.Context, userID string) (bool, error) {
	if err := requireAdmin(ctx); err != nil {
		return false, err
	}
	if _, err := r.Identity.RequestEmailVerification(ctx, &identityv1.RequestEmailVerificationRequest{UserId: userID}); err != nil {
		return false, err
	}
	return true, nil
}

// ConfirmEmailVerification is the resolver for the confirmEmailVerification field.
// Keyed by the emailed code (plus userId or email); returns false for a
// wrong/expired code without revealing whether the account exists.
func (r *mutationResolver) ConfirmEmailVerification(ctx context.Context, userID *string, email *string, code string) (bool, error) {
	req := &identityv1.ConfirmEmailVerificationRequest{Code: code}
	if userID != nil {
		req.UserId = *userID
	}
	if email != nil {
		req.Email = *email
	}
	resp, err := r.Identity.ConfirmEmailVerification(ctx, req)
	if err != nil {
		return false, err
	}
	return resp.GetOk(), nil
}

// SetUserRoles is the resolver for the setUserRoles field.
func (r *mutationResolver) SetUserRoles(ctx context.Context, userID string, roles []string) (*User, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	resp, err := r.Identity.SetUserRoles(ctx, &identityv1.SetUserRolesRequest{UserId: userID, Roles: roles, ActingUserId: actorFrom(ctx)})
	if err != nil {
		return nil, err
	}
	return gqlUser(resp.GetUser()), nil
}

// SetUserDisabled is the resolver for the setUserDisabled field.
func (r *mutationResolver) SetUserDisabled(ctx context.Context, userID string, disabled bool) (*User, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	if disabled && userID == actorFrom(ctx) {
		return nil, errors.New("you cannot disable your own account")
	}
	resp, err := r.Identity.SetUserDisabled(ctx, &identityv1.SetUserDisabledRequest{UserId: userID, Disabled: disabled, ActingUserId: actorFrom(ctx)})
	if err != nil {
		return nil, err
	}
	return gqlUser(resp.GetUser()), nil
}

// RevokeMyToken is the resolver for the revokeMyToken field.
func (r *mutationResolver) RevokeMyToken(ctx context.Context, id string) (*UserToken, error) {
	me := actorFrom(ctx)
	if me == "" {
		return nil, errors.New("not signed in")
	}
	resp, err := r.Identity.RevokeUserToken(ctx, &identityv1.RevokeUserTokenRequest{Id: id, UserId: me, ActingUserId: me})
	if err != nil {
		return nil, err
	}
	return gqlUserToken(resp.GetMeta()), nil
}

// DecideSecretUse is the resolver for the decideSecretUse field.
func (r *mutationResolver) DecideSecretUse(ctx context.Context, id string, approve bool, factor *FactorInput) (*SecretUse, error) {
	me, err := signedIn(ctx)
	if err != nil {
		return nil, err
	}
	if approve {
		if err := r.requireFactor(ctx, me, factor); err != nil {
			return nil, err
		}
	}
	resp, err := r.Vault.DecideSecretUse(ctx, &vaultv1.DecideSecretUseRequest{Actor: actorOf(ctx), UseId: id, Approve: approve})
	if err != nil {
		return nil, err
	}
	return secretUseOf(resp.GetUse()), nil
}

// CreateUseGrant is the resolver for the createUseGrant field.
func (r *mutationResolver) CreateUseGrant(ctx context.Context, input UseGrantInput, factor FactorInput) (*UseGrant, error) {
	me, err := signedIn(ctx)
	if err != nil {
		return nil, err
	}
	owned, err := r.ownsToken(ctx, me, input.TokenID)
	if err != nil {
		return nil, err
	}
	if !owned {
		return nil, errors.New("grants can only be made for your own active tokens")
	}
	if err := r.requireFactor(ctx, me, &factor); err != nil {
		return nil, err
	}
	resp, err := r.Vault.CreateUseGrant(ctx, &vaultv1.CreateUseGrantRequest{Actor: actorOf(ctx), Grant: useGrantProto(input)})
	if err != nil {
		return nil, err
	}
	return useGrantOf(resp.GetGrant()), nil
}

// RevokeUseGrant is the resolver for the revokeUseGrant field.
func (r *mutationResolver) RevokeUseGrant(ctx context.Context, id string) (*UseGrant, error) {
	if _, err := signedIn(ctx); err != nil {
		return nil, err
	}
	resp, err := r.Vault.RevokeUseGrant(ctx, &vaultv1.RevokeUseGrantRequest{Actor: actorOf(ctx), GrantId: id})
	if err != nil {
		return nil, err
	}
	return useGrantOf(resp.GetGrant()), nil
}

// SendMfaEmailCode is the resolver for the sendMfaEmailCode field.
func (r *mutationResolver) SendMfaEmailCode(ctx context.Context) (bool, error) {
	me, err := signedIn(ctx)
	if err != nil {
		return false, err
	}
	if _, err := r.Identity.SendEmailOtp(ctx, &identityv1.SendEmailOtpRequest{UserId: me, Purpose: mfaEmailPurpose}); err != nil {
		return false, err
	}
	return true, nil
}

// BeginMfaPasskey is the resolver for the beginMfaPasskey field.
func (r *mutationResolver) BeginMfaPasskey(ctx context.Context) (*PasskeyChallenge, error) {
	me, err := signedIn(ctx)
	if err != nil {
		return nil, err
	}
	resp, err := r.Identity.WebauthnAssertBegin(ctx, &identityv1.WebauthnAssertBeginRequest{UserId: me})
	if err != nil {
		return nil, err
	}
	return &PasskeyChallenge{Options: resp.GetOptionsJson(), WebauthnSessionID: resp.GetSessionId()}, nil
}

// RevokeUserToken is the resolver for the revokeUserToken field.
func (r *mutationResolver) RevokeUserToken(ctx context.Context, userID string, id string) (*UserToken, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	resp, err := r.Identity.RevokeUserToken(ctx, &identityv1.RevokeUserTokenRequest{Id: id, UserId: userID, ActingUserId: actorFrom(ctx)})
	if err != nil {
		return nil, err
	}
	return gqlUserToken(resp.GetMeta()), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, userID string, name string, email string, username string) (*User, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	resp, err := r.Identity.UpdateUser(ctx, &identityv1.UpdateUserRequest{
		UserId:       userID,
		Name:         name,
		Email:        email,
		Username:     username,
		ActingUserId: actorFrom(ctx),
	})
	if err != nil {
		return nil, err
	}
	return gqlUser(resp.GetUser()), nil
}

// MarkNotificationRead is the resolver for the markNotificationRead field.
func (r *mutationResolver) MarkNotificationRead(ctx context.Context, id string) (bool, error) {
	resp, err := r.Notify.MarkRead(ctx, &notifyv1.MarkReadRequest{UserId: actorFrom(ctx), Id: id})
	if err != nil {
		return false, err
	}
	return resp.GetOk(), nil
}

// MarkAllNotificationsRead is the resolver for the markAllNotificationsRead field.
func (r *mutationResolver) MarkAllNotificationsRead(ctx context.Context) (bool, error) {
	if _, err := r.Notify.MarkAllRead(ctx, &notifyv1.MarkAllReadRequest{UserId: actorFrom(ctx)}); err != nil {
		return false, err
	}
	return true, nil
}

// OpenSSHSession is the resolver for the openSshSession field.
func (r *mutationResolver) OpenSSHSession(ctx context.Context, secretID string) (*SSHSessionTicket, error) {
	actor := actorOf(ctx)
	sec, err := r.Vault.GetSecret(ctx, &vaultv1.GetSecretRequest{Actor: actor, Id: secretID})
	if err != nil {
		return nil, err
	}
	if sec.GetSecret().GetTypeId() != "type-ssh-key" {
		return nil, fmt.Errorf("secret is not an SSH key")
	}
	targetID := sec.GetSecret().GetTargetId()
	if targetID == "" {
		return nil, fmt.Errorf("secret has no target host")
	}
	host, port, hostKeys, err := r.resolveSSHEndpoint(ctx, targetID)
	if err != nil {
		return nil, err
	}
	// Non-sensitive username (no audited reveal).
	fields, err := r.Vault.GetSecretFields(ctx, &vaultv1.GetSecretFieldsRequest{Actor: actor, Id: secretID})
	if err != nil {
		return nil, err
	}
	// Hand the broker a REFERENCE (secret id + actor), not the key. The broker
	// can run >1 replica: it stores only the reference in a shared ticket store
	// and, on the pod that terminates the SSH session, reveals the private key
	// from the vault itself (RevealSecretField, RBAC-gated + audited) with this
	// same actor. So the key is never fetched/forwarded here — it stays in the
	// vault until the redeeming pod needs it, and RBAC/audit are unchanged
	// because the broker passes this actor straight through.
	resp, err := r.SSHBroker.CreateSession(ctx, &sshbrokerv1.CreateSessionRequest{
		Host:        host,
		Port:        safeconv.Int32(port),
		Username:    fields.GetFields()["username"],
		ActorUserId: actor.GetUserId(),
		SecretId:    secretID,
		TargetId:    targetID,
		TtlSeconds:  30,
		HostKeys:    hostKeys,
		Actor:       brokerActor(actor),
	})
	if err != nil {
		return nil, err
	}
	return &SSHSessionTicket{
		WsURL:            resp.GetWsUrl(),
		Ticket:           resp.GetTicket(),
		SessionID:        resp.GetSessionId(),
		ExpiresInSeconds: int(resp.GetExpiresInSeconds()),
	}, nil
}

// CreateServiceAccount is the resolver for the createServiceAccount field.
// Admin-gated: only a site-admin or root may provision a new machine
// principal.
func (r *mutationResolver) CreateServiceAccount(ctx context.Context, name string, description string) (*ServiceAccount, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	resp, err := r.Identity.CreateServiceAccount(ctx, &identityv1.CreateServiceAccountRequest{
		Name: name, Description: description, CreatedBy: actorFrom(ctx),
	})
	if err != nil {
		return nil, err
	}
	return gqlServiceAccount(resp.GetServiceAccount()), nil
}

// DisableServiceAccount is the resolver for the disableServiceAccount field.
// Admin-gated. Soft-disable (no delete): tokens already minted keep their own
// independent expiry/revocation state. Returns the updated service account.
func (r *mutationResolver) DisableServiceAccount(ctx context.Context, id string) (*ServiceAccount, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	resp, err := r.Identity.DisableServiceAccount(ctx, &identityv1.DisableServiceAccountRequest{Id: id, ActingUserId: actorFrom(ctx)})
	if err != nil {
		return nil, err
	}
	return gqlServiceAccount(resp.GetServiceAccount()), nil
}

// MintAPIToken is the resolver for the mintApiToken field. Admin-gated. The
// plaintext token is minted and returned exactly once, in this result — the
// gateway never logs the token value, only the minted token's id (carried on
// its metadata for the caller to log if it chooses).
func (r *mutationResolver) MintAPIToken(ctx context.Context, serviceAccountID string, scope string, expiresAt *int) (*MintAPITokenResult, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	var expiresAtUnix int64
	if expiresAt != nil {
		expiresAtUnix = int64(*expiresAt)
	}
	resp, err := r.Identity.MintApiToken(ctx, &identityv1.MintApiTokenRequest{
		ServiceAccountId: serviceAccountID, Scope: scope, ExpiresAtUnix: expiresAtUnix, CreatedBy: actorFrom(ctx),
	})
	if err != nil {
		return nil, err
	}
	return &MintAPITokenResult{Token: resp.GetToken(), APIToken: gqlAPIToken(resp.GetMeta())}, nil
}

// RevokeAPIToken is the resolver for the revokeApiToken field. Admin-gated.
// Returns the token's updated metadata (never the token value, which was
// never stored past mint time).
func (r *mutationResolver) RevokeAPIToken(ctx context.Context, id string) (*APIToken, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	resp, err := r.Identity.RevokeApiToken(ctx, &identityv1.RevokeApiTokenRequest{Id: id, ActingUserId: actorFrom(ctx)})
	if err != nil {
		return nil, err
	}
	return gqlAPIToken(resp.GetMeta()), nil
}

// LinkOidcClient is the resolver for the linkOidcClient field. Admin-gated
// mutation: links an OIDC/OAuth2 client (Ory Hydra client-credentials) to a
// service account. The issuer is always the gateway's own configured Hydra
// issuer (r.HydraIssuer) — never caller-supplied. allowedGroups is the
// admin-set trust bound forwarded to identity, which validates each entry
// (group ID, exact name or slug) and stores group IDs;
// identity later grants JWT scope groups INTERSECT this bound. An empty list
// grants no groups.
func (r *mutationResolver) LinkOidcClient(ctx context.Context, serviceAccountID string, oidcSubject string, allowedGroups []string) (*ServiceAccount, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	resp, err := r.Identity.LinkOidcClient(ctx, &identityv1.LinkOidcClientRequest{
		ServiceAccountId: serviceAccountID, OidcIssuer: r.HydraIssuer, OidcSubject: oidcSubject, ActingAdmin: actorFrom(ctx),
		AllowedGroups: allowedGroups,
	})
	if err != nil {
		return nil, err
	}
	return gqlServiceAccount(resp.GetServiceAccount()), nil
}

// UnlinkOidcClient is the resolver for the unlinkOidcClient field.
// Admin-gated. Removes a service account's OIDC client
// linkage; its opaque API-token path is unaffected.
func (r *mutationResolver) UnlinkOidcClient(ctx context.Context, serviceAccountID string) (*ServiceAccount, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	resp, err := r.Identity.UnlinkOidcClient(ctx, &identityv1.UnlinkOidcClientRequest{
		ServiceAccountId: serviceAccountID, ActingAdmin: actorFrom(ctx),
	})
	if err != nil {
		return nil, err
	}
	return gqlServiceAccount(resp.GetServiceAccount()), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*User, error) {
	resp, err := r.Identity.ListUsers(ctx, &identityv1.ListUsersRequest{})
	if err != nil {
		return nil, err
	}
	out := make([]*User, 0, len(resp.GetUsers()))
	for _, u := range resp.GetUsers() {
		out = append(out, gqlUser(u))
	}
	return out, nil
}

// User is the resolver for the user field: a single user by id (nil when the
// identity directory has no such user).
func (r *queryResolver) User(ctx context.Context, id string) (*User, error) {
	resp, err := r.Identity.GetUser(ctx, &identityv1.GetUserRequest{Id: id})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return nil, nil
		}
		return nil, err
	}
	return gqlUser(resp.GetUser()), nil
}

// Groups is the resolver for the groups field.
func (r *queryResolver) Groups(ctx context.Context) ([]*Group, error) {
	resp, err := r.Identity.ListGroups(ctx, &identityv1.ListGroupsRequest{})
	if err != nil {
		return nil, err
	}
	out := make([]*Group, 0, len(resp.GetGroups()))
	for _, g := range resp.GetGroups() {
		out = append(out, &Group{ID: g.GetId(), Name: g.GetName()})
	}
	return out, nil
}

// UserGroups is the resolver for the userGroups field: the directory groups a
// user is a direct member of.
func (r *queryResolver) UserGroups(ctx context.Context, userID string) ([]*Group, error) {
	resp, err := r.Identity.ListUserGroups(ctx, &identityv1.ListUserGroupsRequest{UserId: userID})
	if err != nil {
		return nil, err
	}
	out := make([]*Group, 0, len(resp.GetGroups()))
	for _, g := range resp.GetGroups() {
		out = append(out, &Group{ID: g.GetId(), Name: g.GetName()})
	}
	return out, nil
}

// GroupMembers is the resolver for the groupMembers field: the users who are
// direct members of a group.
func (r *queryResolver) GroupMembers(ctx context.Context, groupID string) ([]*User, error) {
	resp, err := r.Identity.ListGroupMembers(ctx, &identityv1.ListGroupMembersRequest{GroupId: groupID})
	if err != nil {
		return nil, err
	}
	out := make([]*User, 0, len(resp.GetUsers()))
	for _, u := range resp.GetUsers() {
		out = append(out, gqlUser(u))
	}
	return out, nil
}

// UserAdGroups is the resolver for the userAdGroups field: retired, always
// empty (identity no longer syncs AD groups).
func (r *queryResolver) UserAdGroups(ctx context.Context, userID string) ([]string, error) {
	resp, err := r.Identity.UserAdGroups(ctx, &identityv1.UserAdGroupsRequest{UserId: userID}) //nolint:staticcheck // kept until the UI drops its AD-groups section, then the field goes too
	if err != nil {
		return nil, err
	}
	names := resp.GetNames()
	if names == nil {
		names = []string{}
	}
	return names, nil
}

// SearchUsers is the resolver for the searchUsers field: a typeahead search
// over users, for picking RACI subjects / simulator actors.
func (r *queryResolver) SearchUsers(ctx context.Context, query string, limit *int) ([]*User, error) {
	resp, err := r.Identity.SearchUsers(ctx, &identityv1.SearchUsersRequest{Query: query, Limit: int32(ideref(limit))})
	if err != nil {
		return nil, err
	}
	out := make([]*User, 0, len(resp.GetUsers()))
	for _, u := range resp.GetUsers() {
		out = append(out, gqlUser(u))
	}
	return out, nil
}

// ResolveUserLabels is the resolver for the resolveUserLabels field: resolves
// a batch of user ids to display labels (id + name).
func (r *queryResolver) ResolveUserLabels(ctx context.Context, ids []string) ([]*UserLabel, error) {
	resp, err := r.Identity.ResolveUserLabels(ctx, &identityv1.ResolveUserLabelsRequest{Ids: ids})
	if err != nil {
		return nil, err
	}
	out := make([]*UserLabel, 0, len(resp.GetLabels()))
	for _, l := range resp.GetLabels() {
		out = append(out, &UserLabel{ID: l.GetId(), Name: l.GetName()})
	}
	return out, nil
}

// SimulateFolder is the resolver for the simulateFolder field: previews the
// effective RACI decision for userId on a folder if draftRules (not yet
// saved) were in effect, without persisting anything.
func (r *queryResolver) SimulateFolder(ctx context.Context, folderID string, userID string, draftRules []*RaciRuleInput) (*RaciDecision, error) {
	simIsSiteAdmin, simIsRoot, err := r.simActorAttrs(ctx, userID)
	if err != nil {
		return nil, err
	}
	protoRules := make([]*vaultv1.RaciRule, 0, len(draftRules))
	for _, in := range draftRules {
		protoRules = append(protoRules, protoRaciRuleInput(in))
	}
	resp, err := r.Vault.SimulateFolder(ctx, &vaultv1.SimulateFolderRequest{
		Actor: actorOf(ctx), FolderId: folderID, SimUserId: userID,
		SimIsSiteAdmin: simIsSiteAdmin, SimIsRoot: simIsRoot, SimGroupNames: nil,
		DraftRules: protoRules,
	})
	if err != nil {
		return nil, err
	}
	return gqlRaciDecision(resp.GetDecision()), nil
}

// SimulateSecret is the resolver for the simulateSecret field: previews the
// effective RACI decision for userId on a secret if draftRules (not yet
// saved) were in effect, without persisting anything.
func (r *queryResolver) SimulateSecret(ctx context.Context, secretID string, userID string, draftRules []*RaciRuleInput) (*RaciDecision, error) {
	simIsSiteAdmin, simIsRoot, err := r.simActorAttrs(ctx, userID)
	if err != nil {
		return nil, err
	}
	protoRules := make([]*vaultv1.RaciRule, 0, len(draftRules))
	for _, in := range draftRules {
		protoRules = append(protoRules, protoRaciRuleInput(in))
	}
	resp, err := r.Vault.SimulateSecret(ctx, &vaultv1.SimulateSecretRequest{
		Actor: actorOf(ctx), SecretId: secretID, SimUserId: userID,
		SimIsSiteAdmin: simIsSiteAdmin, SimIsRoot: simIsRoot, SimGroupNames: nil,
		DraftRules: protoRules,
	})
	if err != nil {
		return nil, err
	}
	return gqlRaciDecision(resp.GetDecision()), nil
}

// ActiveLeasesForUser is the resolver for the activeLeasesForUser field.
func (r *queryResolver) ActiveLeasesForUser(ctx context.Context, userID string) ([]*Lease, error) {
	resp, err := r.Workflow.ListActiveLeasesForUser(ctx, &workflowv1.ListActiveLeasesForUserRequest{UserId: userID})
	if err != nil {
		return nil, err
	}
	out := make([]*Lease, 0, len(resp.GetLeases()))
	for _, l := range resp.GetLeases() {
		out = append(out, gqlLease(l))
	}
	return out, nil
}

// ActiveLease is the resolver for the activeLease field.
func (r *queryResolver) ActiveLease(ctx context.Context, secretID string) (*Lease, error) {
	resp, err := r.Workflow.GetActiveLease(ctx, &workflowv1.GetActiveLeaseRequest{SecretId: secretID})
	if err != nil {
		return nil, err
	}
	if resp.GetLease() == nil || resp.GetLease().GetId() == "" {
		return nil, nil
	}
	return gqlLease(resp.GetLease()), nil
}

// ApprovalRequests is the resolver for the approvalRequests field.
func (r *queryResolver) ApprovalRequests(ctx context.Context) ([]*ApprovalRequest, error) {
	resp, err := r.Workflow.ListApprovalRequests(ctx, &workflowv1.ListApprovalRequestsRequest{})
	if err != nil {
		return nil, err
	}
	out := make([]*ApprovalRequest, 0, len(resp.GetRequests()))
	for _, req := range resp.GetRequests() {
		out = append(out, gqlApproval(req))
	}
	r.enrichApprovalNames(ctx, out)
	return out, nil
}

// Connections is the resolver for the connections field.
func (r *queryResolver) Connections(ctx context.Context) ([]*Connection, error) {
	resp, err := r.Vault.ListConnections(ctx, &vaultv1.ListConnectionsRequest{})
	if err != nil {
		return nil, err
	}
	out := make([]*Connection, 0, len(resp.GetConnections()))
	for _, c := range resp.GetConnections() {
		out = append(out, gqlConnection(c))
	}
	return out, nil
}

// Targets is the resolver for the targets field.
func (r *queryResolver) Targets(ctx context.Context) ([]*Target, error) {
	resp, err := r.Vault.ListTargets(ctx, &vaultv1.ListTargetsRequest{Actor: actorOf(ctx)})
	if err != nil {
		return nil, err
	}
	out := make([]*Target, 0, len(resp.GetTargets()))
	for _, t := range resp.GetTargets() {
		out = append(out, gqlTarget(t))
	}
	return out, nil
}

// PasswordPolicies is the resolver for the passwordPolicies field.
func (r *queryResolver) PasswordPolicies(ctx context.Context) ([]*PasswordPolicy, error) {
	resp, err := r.Vault.ListPasswordPolicies(ctx, &vaultv1.ListPasswordPoliciesRequest{})
	if err != nil {
		return nil, err
	}
	out := make([]*PasswordPolicy, 0, len(resp.GetPolicies()))
	for _, p := range resp.GetPolicies() {
		out = append(out, gqlPolicy(p))
	}
	return out, nil
}

// SecuritySettings is the resolver for the securitySettings field.
func (r *queryResolver) SecuritySettings(ctx context.Context) (*SecuritySettings, error) {
	resp, err := r.Vault.GetSecuritySettings(ctx, &vaultv1.GetSecuritySettingsRequest{})
	if err != nil {
		return nil, err
	}
	return gqlSettings(resp.GetSettings()), nil
}

// SecretTypes is the resolver for the secretTypes field.
func (r *queryResolver) SecretTypes(ctx context.Context) ([]*SecretType, error) {
	resp, err := r.Vault.ListSecretTypes(ctx, &vaultv1.ListSecretTypesRequest{})
	if err != nil {
		return nil, err
	}
	out := make([]*SecretType, 0, len(resp.GetTypes()))
	for _, t := range resp.GetTypes() {
		out = append(out, gqlType(t))
	}
	return out, nil
}

// AvailableExtensions is the resolver for the availableExtensions field.
func (r *queryResolver) AvailableExtensions(ctx context.Context) ([]*SecretType, error) {
	resp, err := r.Vault.ListAvailableExtensions(ctx, &vaultv1.ListAvailableExtensionsRequest{})
	if err != nil {
		return nil, err
	}
	out := make([]*SecretType, 0, len(resp.GetExtensions()))
	for _, e := range resp.GetExtensions() {
		out = append(out, gqlType(e))
	}
	return out, nil
}

// Folders is the resolver for the folders field.
func (r *queryResolver) Folders(ctx context.Context) ([]*Folder, error) {
	resp, err := r.Vault.ListFolders(ctx, &vaultv1.ListFoldersRequest{Actor: actorOf(ctx)})
	if err != nil {
		return nil, err
	}
	out := make([]*Folder, 0, len(resp.GetFolders()))
	for _, f := range resp.GetFolders() {
		out = append(out, gqlFolder(f))
	}
	return out, nil
}

// SecretsInFolder is the resolver for the secretsInFolder field.
func (r *queryResolver) SecretsInFolder(ctx context.Context, folderID string, includeRetired *bool) ([]*Secret, error) {
	resp, err := r.Vault.ListSecretsInFolder(ctx, &vaultv1.ListSecretsInFolderRequest{
		Actor: actorOf(ctx), FolderId: folderID, IncludeRetired: bderef(includeRetired),
	})
	if err != nil {
		return nil, err
	}
	out := make([]*Secret, 0, len(resp.GetSecrets()))
	for _, s := range resp.GetSecrets() {
		out = append(out, gqlSecret(s))
	}
	return out, nil
}

// Secret is the resolver for the secret field.
func (r *queryResolver) Secret(ctx context.Context, id string) (*Secret, error) {
	resp, err := r.Vault.GetSecret(ctx, &vaultv1.GetSecretRequest{Actor: actorOf(ctx), Id: id})
	if status.Code(err) == codes.NotFound {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return gqlSecret(resp.GetSecret()), nil
}

// SecretStats is the resolver for the secretStats field.
func (r *queryResolver) SecretStats(ctx context.Context) (*SecretStats, error) {
	resp, err := r.Vault.GetSecretStats(ctx, &vaultv1.GetSecretStatsRequest{Actor: actorOf(ctx)})
	if err != nil {
		return nil, err
	}
	st := resp.GetStats()
	return &SecretStats{
		Total: int(st.GetTotal()), ExpiringSoon: int(st.GetExpiringSoon()),
		Expired: int(st.GetExpired()), Drift: int(st.GetDrift()),
	}, nil
}

// TopAccessedSecrets is the resolver for the topAccessedSecrets field.
func (r *queryResolver) TopAccessedSecrets(ctx context.Context, limit *int) ([]*Secret, error) {
	var lim int32
	if limit != nil {
		lim = safeconv.Int32(*limit)
	}
	resp, err := r.Vault.GetTopAccessedSecrets(ctx, &vaultv1.GetTopAccessedSecretsRequest{Actor: actorOf(ctx), Limit: lim})
	if err != nil {
		return nil, err
	}
	out := make([]*Secret, 0, len(resp.GetSecrets()))
	for _, sec := range resp.GetSecrets() {
		out = append(out, gqlSecret(sec))
	}
	return out, nil
}

// SecretsByStatus is the resolver for the secretsByStatus field.
func (r *queryResolver) SecretsByStatus(ctx context.Context, status string) ([]*Secret, error) {
	resp, err := r.Vault.ListSecretsByStatus(ctx, &vaultv1.ListSecretsByStatusRequest{Actor: actorOf(ctx), Status: status})
	if err != nil {
		return nil, err
	}
	out := make([]*Secret, 0, len(resp.GetSecrets()))
	for _, sec := range resp.GetSecrets() {
		out = append(out, gqlSecret(sec))
	}
	return out, nil
}

// FindSecretsByPublicKey is the resolver for the findSecretsByPublicKey field.
func (r *queryResolver) FindSecretsByPublicKey(ctx context.Context, query string) ([]*Secret, error) {
	resp, err := r.Vault.FindSecretsByPublicKey(ctx, &vaultv1.FindSecretsByPublicKeyRequest{Actor: actorOf(ctx), Query: query})
	if err != nil {
		return nil, err
	}
	out := make([]*Secret, 0, len(resp.GetSecrets()))
	for _, sec := range resp.GetSecrets() {
		out = append(out, gqlSecret(sec))
	}
	return out, nil
}

// SecretFields is the resolver for the secretFields field.
func (r *queryResolver) SecretFields(ctx context.Context, id string) ([]*KeyValue, error) {
	resp, err := r.Vault.GetSecretFields(ctx, &vaultv1.GetSecretFieldsRequest{Actor: actorOf(ctx), Id: id})
	if err != nil {
		return nil, err
	}
	out := make([]*KeyValue, 0, len(resp.GetFields()))
	for k, v := range resp.GetFields() {
		out = append(out, &KeyValue{Key: k, Value: v})
	}
	return out, nil
}

// SecretVersions is the resolver for the secretVersions field.
func (r *queryResolver) SecretVersions(ctx context.Context, secretID string) ([]*SecretVersion, error) {
	resp, err := r.Vault.ListSecretVersions(ctx, &vaultv1.ListSecretVersionsRequest{Actor: actorOf(ctx), SecretId: secretID})
	if err != nil {
		return nil, err
	}
	vers := resp.GetVersions()
	names := r.resolveCreatedByNames(ctx, vers)
	out := make([]*SecretVersion, 0, len(vers))
	for _, v := range vers {
		name := names[v.GetCreatedBy()]
		if name == "" {
			name = v.GetCreatedBy()
		}
		out = append(out, gqlSecretVersion(v, name))
	}
	return out, nil
}

// FolderRules is the resolver for the folderRules field.
func (r *queryResolver) FolderRules(ctx context.Context, folderID string) ([]*FolderAccessRule, error) {
	resp, err := r.Vault.ListFolderRules(ctx, &vaultv1.ListFolderRulesRequest{FolderId: folderID})
	if err != nil {
		return nil, err
	}
	out := make([]*FolderAccessRule, 0, len(resp.GetRules()))
	for _, rule := range resp.GetRules() {
		out = append(out, gqlRule(rule))
	}
	return out, nil
}

// InheritedFolderRules is the resolver for the inheritedFolderRules field.
func (r *queryResolver) InheritedFolderRules(ctx context.Context, folderID string) ([]*InheritedFolderRule, error) {
	resp, err := r.Vault.GetInheritedFolderRules(ctx, &vaultv1.GetInheritedFolderRulesRequest{FolderId: folderID})
	if err != nil {
		return nil, err
	}
	out := make([]*InheritedFolderRule, 0, len(resp.GetRules()))
	for _, ir := range resp.GetRules() {
		out = append(out, &InheritedFolderRule{Rule: gqlRule(ir.GetRule()), FromFolderID: ir.GetFromFolderId(), FromFolderName: ir.GetFromFolderName()})
	}
	return out, nil
}

// FolderRuleset is the resolver for the folderRuleset field: a folder's own
// firewall-RACI ruleset (owners + ordered rules) plus the rules it inherits
// from ancestor folders (read-only, tagged with their source).
func (r *queryResolver) FolderRuleset(ctx context.Context, folderID string) (*FolderRuleset, error) {
	return r.buildFolderRuleset(ctx, folderID)
}

// MyFolderAccess is the resolver for the myFolderAccess field: the acting user's
// effective RACI access on a folder (Resolve over the folder chain).
func (r *queryResolver) MyFolderAccess(ctx context.Context, folderID string) (*FolderAccess, error) {
	resp, err := r.Vault.GetMyAccess(ctx, &vaultv1.GetMyAccessRequest{Actor: actorOf(ctx), FolderId: folderID})
	if err != nil {
		return nil, err
	}
	return gqlFolderAccess(resp.GetAccess()), nil
}

// SecretRuleset is the resolver for the secretRuleset field.
func (r *queryResolver) SecretRuleset(ctx context.Context, secretID string) (*SecretRuleset, error) {
	return r.buildSecretRuleset(ctx, secretID)
}

// MySecretAccess is the resolver for the mySecretAccess field: the acting
// user's effective RACI access on a secret (resolved over its own ruleset plus
// its folder chain).
func (r *queryResolver) MySecretAccess(ctx context.Context, secretID string) (*FolderAccess, error) {
	resp, err := r.Vault.GetMySecretAccess(ctx, &vaultv1.GetMySecretAccessRequest{Actor: actorOf(ctx), SecretId: secretID})
	if err != nil {
		return nil, err
	}
	return gqlFolderAccess(resp.GetAccess()), nil
}

// MyNotifications is the resolver for the myNotifications field.
func (r *queryResolver) MyNotifications(ctx context.Context, limit *int) ([]*Notification, error) {
	var lim int32
	if limit != nil {
		lim = safeconv.Int32(*limit)
	}
	resp, err := r.Notify.ListNotifications(ctx, &notifyv1.ListNotificationsRequest{UserId: actorFrom(ctx), Limit: lim})
	if err != nil {
		return nil, err
	}
	out := make([]*Notification, 0, len(resp.GetNotifications()))
	for _, n := range resp.GetNotifications() {
		out = append(out, gqlNotification(n))
	}
	return out, nil
}

// MyUnreadNotificationCount is the resolver for the myUnreadNotificationCount field.
func (r *queryResolver) MyUnreadNotificationCount(ctx context.Context) (int, error) {
	resp, err := r.Notify.UnreadCount(ctx, &notifyv1.UnreadCountRequest{UserId: actorFrom(ctx)})
	if err != nil {
		return 0, err
	}
	return int(resp.GetCount()), nil
}

// AuditRecords is the resolver for the auditRecords field.
func (r *queryResolver) AuditRecords(ctx context.Context, actorUserID *string, subject *string, excludeActions []string, limit *int) ([]*AuditRecord, error) {
	return r.listAuditRecords(ctx, actorUserID, subject, excludeActions, limit)
}

// AuditActions is the resolver for the auditActions field.
func (r *queryResolver) AuditActions(ctx context.Context) ([]string, error) {
	return r.listAuditActions(ctx)
}

// AuditChain is the resolver for the auditChain field.
func (r *queryResolver) AuditChain(ctx context.Context) (*AuditChainStatus, error) {
	return r.verifyAuditChain(ctx)
}

// ServiceAccounts is the resolver for the serviceAccounts field. Admin-gated:
// only a site-admin or root may list machine principals.
func (r *queryResolver) ServiceAccounts(ctx context.Context) ([]*ServiceAccount, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	resp, err := r.Identity.ListServiceAccounts(ctx, &identityv1.ListServiceAccountsRequest{})
	if err != nil {
		return nil, err
	}
	out := make([]*ServiceAccount, 0, len(resp.GetServiceAccounts()))
	for _, sa := range resp.GetServiceAccounts() {
		out = append(out, gqlServiceAccount(sa))
	}
	return out, nil
}

// APITokens is the resolver for the apiTokens field. Admin-gated. Metadata
// only — never a token value (ApiToken has no token field on the wire or in
// the schema).
func (r *queryResolver) APITokens(ctx context.Context, serviceAccountID string) ([]*APIToken, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	resp, err := r.Identity.ListApiTokens(ctx, &identityv1.ListApiTokensRequest{ServiceAccountId: serviceAccountID})
	if err != nil {
		return nil, err
	}
	out := make([]*APIToken, 0, len(resp.GetTokens()))
	for _, t := range resp.GetTokens() {
		out = append(out, gqlAPIToken(t))
	}
	return out, nil
}

// MyTokens is the resolver for the myTokens field.
func (r *queryResolver) MyTokens(ctx context.Context) ([]*UserToken, error) {
	me := actorFrom(ctx)
	if me == "" {
		return nil, errors.New("not signed in")
	}
	return r.listUserTokens(ctx, me)
}

// PendingSecretUses is the resolver for the pendingSecretUses field.
func (r *queryResolver) PendingSecretUses(ctx context.Context) ([]*SecretUse, error) {
	if _, err := signedIn(ctx); err != nil {
		return nil, err
	}
	resp, err := r.Vault.ListPendingSecretUses(ctx, &vaultv1.ListPendingSecretUsesRequest{Actor: actorOf(ctx)})
	if err != nil {
		return nil, err
	}
	out := make([]*SecretUse, 0, len(resp.GetUses()))
	for _, u := range resp.GetUses() {
		out = append(out, secretUseOf(u))
	}
	return out, nil
}

// UseGrants is the resolver for the useGrants field.
func (r *queryResolver) UseGrants(ctx context.Context) ([]*UseGrant, error) {
	if _, err := signedIn(ctx); err != nil {
		return nil, err
	}
	resp, err := r.Vault.ListUseGrants(ctx, &vaultv1.ListUseGrantsRequest{Actor: actorOf(ctx)})
	if err != nil {
		return nil, err
	}
	out := make([]*UseGrant, 0, len(resp.GetGrants()))
	for _, g := range resp.GetGrants() {
		out = append(out, useGrantOf(g))
	}
	return out, nil
}

// UserTokens is the resolver for the userTokens field.
func (r *queryResolver) UserTokens(ctx context.Context, userID string) ([]*UserToken, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	return r.listUserTokens(ctx, userID)
}

// SecretStats is the resolver for the secretStats subscription: it pushes the
// acting user's dashboard rollup over the WebSocket. RACI scoping is automatic —
// actorOf(ctx) carries the socket's authenticated actor (resolved from the
// session cookie in the WS InitFunc), so GetSecretStats returns exactly the
// same readable-secrets rollup as the secretStats query. It emits once
// immediately on subscribe, then on a ticker pushes only when the value changed,
// and stops when the client disconnects (ctx.Done()).
func (r *subscriptionResolver) SecretStats(ctx context.Context) (<-chan *SecretStats, error) {
	fetch := func() (*SecretStats, error) {
		resp, err := r.Vault.GetSecretStats(ctx, &vaultv1.GetSecretStatsRequest{Actor: actorOf(ctx)})
		if err != nil {
			return nil, err
		}
		st := resp.GetStats()
		return &SecretStats{
			Total: int(st.GetTotal()), ExpiringSoon: int(st.GetExpiringSoon()),
			Expired: int(st.GetExpired()), Drift: int(st.GetDrift()),
		}, nil
	}
	// Resolve the first snapshot synchronously so an auth/RACI/backend error
	// surfaces as a failed subscription rather than a silently empty stream.
	first, err := fetch()
	if err != nil {
		return nil, err
	}
	ch := make(chan *SecretStats, 1)
	ch <- first
	go func() {
		defer close(ch)
		last := *first
		ticker := time.NewTicker(secretStatsPollInterval)
		defer ticker.Stop()
		for {
			select {
			case <-ctx.Done():
				return
			case <-ticker.C:
				next, ferr := fetch()
				if ferr != nil {
					// Transient backend/identity blip: skip this tick, keep the
					// socket open, try again next interval.
					continue
				}
				if *next == last {
					continue
				}
				last = *next
				select {
				case ch <- next:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
