package machineresolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"strings"

	vaultv1 "github.com/Sneakers-PAM/sneakers-gateway/gen/go/thirdparty/vault/v1"
	"github.com/Sneakers-PAM/sneakers-gateway/internal/resolvers"
	"github.com/Sneakers-PAM/sneakers-gateway/internal/safeconv"
)

// RevealSecretFieldForPrincipal is the resolver for the revealSecretFieldForPrincipal field.
// The actor comes from resolvers.MachineActorOf(ctx) — the machine ActorContext
// bff.MachineActor placed on the context after verifying the caller's
// service-account bearer token. Vault performs the RACI-read check + full
// audit (secret.reveal.principal); no interactive checkout/MFA is consulted
// anywhere in this path.
func (r *mutationResolver) RevealSecretFieldForPrincipal(ctx context.Context, id string, fieldKey string) (string, error) {
	resp, err := r.Vault.RevealSecretFieldForPrincipal(ctx, &vaultv1.RevealSecretFieldForPrincipalRequest{
		Actor: resolvers.MachineActorOf(ctx), Id: id, FieldKey: fieldKey,
	})
	if err != nil {
		return "", err
	}
	return resp.GetValue(), nil
}

// CreateSecretForPrincipal is the resolver for the createSecretForPrincipal
// field. Thin bridge to vault: builds the machine ActorContext, flattens the
// GraphQL field-input list into the map vault expects, and maps the created
// Secret back to a metadata-only summary. placeSecret may swap the folder for
// the caller's Personal folder first. RACI-Author gating, storage, and audit
// all happen in vault.
func (r *mutationResolver) CreateSecretForPrincipal(ctx context.Context, folderID string, typeID string, name string, fields []*SecretFieldInput, targetID *string, disableRotation *bool, disableHeartbeat *bool, keepFolder *bool) (*SecretSummary, error) {
	fm, err := fieldMap(fields)
	if err != nil {
		return nil, err
	}
	placement, err := r.placeSecret(ctx, folderID, name, fm, derefBool(keepFolder))
	if err != nil {
		return nil, err
	}
	resp, err := r.Vault.CreateSecretForPrincipal(ctx, &vaultv1.CreateSecretForPrincipalRequest{
		Actor: resolvers.MachineActorOf(ctx), FolderId: placement.FolderID, TypeId: typeID, Name: name, Fields: fm, TargetId: deref(targetID),
		DisableRotation: derefBool(disableRotation), DisableHeartbeat: derefBool(disableHeartbeat),
	})
	if err != nil {
		return nil, err
	}
	out := summaryOf(resp.GetSecret())
	if out != nil {
		out.Placement = placement
	}
	return out, nil
}

// GenerateSecretForPrincipal is the resolver for the
// generateSecretForPrincipal field. Thin bridge to vault; the generated
// password value is only present on the response (and thus only mapped
// through non-nil by emptyToNil) when the caller passed returnValue: true —
// vault enforces and separately audits that.
func (r *mutationResolver) GenerateSecretForPrincipal(ctx context.Context, folderID string, typeID string, name string, fields []*SecretFieldInput, policyID *string, targetID *string, returnValue *bool, disableRotation *bool, disableHeartbeat *bool, keepFolder *bool) (*GeneratedSecret, error) {
	fm, err := fieldMap(fields)
	if err != nil {
		return nil, err
	}
	placement, err := r.placeSecret(ctx, folderID, name, fm, derefBool(keepFolder))
	if err != nil {
		return nil, err
	}
	resp, err := r.Vault.GenerateSecretForPrincipal(ctx, &vaultv1.GenerateSecretForPrincipalRequest{
		Actor: resolvers.MachineActorOf(ctx), FolderId: placement.FolderID, TypeId: typeID, Name: name, Fields: fm, PolicyId: deref(policyID), TargetId: deref(targetID), ReturnValue: derefBool(returnValue),
		DisableRotation: derefBool(disableRotation), DisableHeartbeat: derefBool(disableHeartbeat),
	})
	if err != nil {
		return nil, err
	}
	secret := summaryOf(resp.GetSecret())
	if secret != nil {
		secret.Placement = placement
	}
	return &GeneratedSecret{Secret: secret, GeneratedValue: emptyToNil(resp.GetGeneratedValue())}, nil
}

// MoveSecretForPrincipal is the resolver for the moveSecretForPrincipal field.
// Thin bridge to vault: the source+destination RACI-Author checks, the
// personal-folder rule and the audit all happen in vault.
func (r *mutationResolver) MoveSecretForPrincipal(ctx context.Context, id string, destFolderID string) (*SecretSummary, error) {
	resp, err := r.Vault.MoveSecretForPrincipal(ctx, &vaultv1.MoveSecretForPrincipalRequest{
		Actor: resolvers.MachineActorOf(ctx), Id: id, DestFolderId: destFolderID,
	})
	if err != nil {
		return nil, err
	}
	return summaryOf(resp.GetSecret()), nil
}

// ChangeSecretTypeForPrincipal is the resolver for the
// changeSecretTypeForPrincipal field. Thin bridge to vault: flattens the
// mapping/field lists (rejecting duplicates rather than last-write-winning),
// and vault does the Author check, the no-value-loss/sensitivity/required
// rules, the managed-type restriction and the audit.
func (r *mutationResolver) ChangeSecretTypeForPrincipal(ctx context.Context, id string, newTypeID string, fieldMapping []*FieldMappingInput, fields []*SecretFieldInput) (*TypeChangedSecret, error) {
	mm, err := mappingMap(fieldMapping)
	if err != nil {
		return nil, err
	}
	fm, err := fieldMap(fields)
	if err != nil {
		return nil, err
	}
	resp, err := r.Vault.ChangeSecretTypeForPrincipal(ctx, &vaultv1.ChangeSecretTypeForPrincipalRequest{
		Actor: resolvers.MachineActorOf(ctx), Id: id, NewTypeId: newTypeID, FieldMapping: mm, Fields: fm,
	})
	if err != nil {
		return nil, err
	}
	keys := resp.GetFieldKeys()
	if keys == nil {
		keys = []string{}
	}
	moved := resp.GetMovedToNotesKeys()
	if moved == nil {
		moved = []string{}
	}
	return &TypeChangedSecret{Secret: summaryOf(resp.GetSecret()), FieldKeys: keys, MovedToNotesKeys: moved}, nil
}

// RenameSecretForPrincipal is the resolver for the renameSecretForPrincipal field.
func (r *mutationResolver) RenameSecretForPrincipal(ctx context.Context, id string, name string) (*SecretSummary, error) {
	resp, err := r.Vault.RenameSecretForPrincipal(ctx, &vaultv1.RenameSecretForPrincipalRequest{
		Actor: resolvers.MachineActorOf(ctx), Id: id, Name: name,
	})
	if err != nil {
		return nil, err
	}
	return summaryOf(resp.GetSecret()), nil
}

// UpdateSecretFieldsForPrincipal is the resolver for the updateSecretFieldsForPrincipal field.
func (r *mutationResolver) UpdateSecretFieldsForPrincipal(ctx context.Context, id string, fields []*SecretFieldInput) (*UpdatedSecretFields, error) {
	fm, err := fieldMap(fields)
	if err != nil {
		return nil, err
	}
	resp, err := r.Vault.UpdateSecretFieldsForPrincipal(ctx, &vaultv1.UpdateSecretFieldsForPrincipalRequest{
		Actor: resolvers.MachineActorOf(ctx), Id: id, Fields: fm,
	})
	if err != nil {
		return nil, err
	}
	keys := resp.GetChangedFieldKeys()
	if keys == nil {
		keys = []string{}
	}
	return &UpdatedSecretFields{Secret: summaryOf(resp.GetSecret()), ChangedFieldKeys: keys}, nil
}

// CreateFolderForPrincipal is the resolver for the createFolderForPrincipal field.
func (r *mutationResolver) CreateFolderForPrincipal(ctx context.Context, parentID string, name string) (*PrincipalFolder, error) {
	resp, err := r.Vault.CreateFolderForPrincipal(ctx, &vaultv1.CreateFolderForPrincipalRequest{
		Actor: resolvers.MachineActorOf(ctx), ParentId: parentID, Name: name,
	})
	if err != nil {
		return nil, err
	}
	return r.visiblePrincipalFolder(ctx, resp.GetFolder()), nil
}

// RenameFolderForPrincipal is the resolver for the renameFolderForPrincipal field.
func (r *mutationResolver) RenameFolderForPrincipal(ctx context.Context, id string, name string) (*PrincipalFolder, error) {
	resp, err := r.Vault.RenameFolderForPrincipal(ctx, &vaultv1.RenameFolderForPrincipalRequest{
		Actor: resolvers.MachineActorOf(ctx), Id: id, Name: name,
	})
	if err != nil {
		return nil, err
	}
	return r.visiblePrincipalFolder(ctx, resp.GetFolder()), nil
}

// RequestSecretCheck is the resolver for the requestSecretCheck field.
func (r *mutationResolver) RequestSecretCheck(ctx context.Context, secretID string) (int, error) {
	resp, err := r.Vault.RequestHeartbeatForPrincipal(ctx, &vaultv1.RequestHeartbeatForPrincipalRequest{Actor: resolvers.MachineActorOf(ctx), SecretId: secretID})
	if err != nil {
		return 0, err
	}
	return safeconv.IntFromInt64(resp.GetRequestedAtUnix()), nil
}

// SaveTargetForPrincipal is the resolver for the saveTargetForPrincipal field.
func (r *mutationResolver) SaveTargetForPrincipal(ctx context.Context, input MachineTargetInput) (*MachineTarget, error) {
	actor := resolvers.MachineActorOf(ctx)
	keys, err := resolvers.HostKeysForSave(ctx, r.Vault, actor, deref(input.ID), input.SSHHostKeys)
	if err != nil {
		return nil, err
	}
	resp, err := r.Vault.SaveTarget(ctx, &vaultv1.SaveTargetRequest{Actor: actor, Target: &vaultv1.Target{
		Id: deref(input.ID), Name: input.Name, Hostname: input.Hostname, Kind: deref(input.Kind), Domain: deref(input.Domain),
		Realm: deref(input.Realm), ConnectionId: input.ConnectionID, Description: deref(input.Description),
		SshHostKeys: keys,
	}})
	if err != nil {
		return nil, err
	}
	return targetOf(resp.GetTarget()), nil
}

// SetSecretTargetForPrincipal is the resolver for the setSecretTargetForPrincipal field.
func (r *mutationResolver) SetSecretTargetForPrincipal(ctx context.Context, secretID string, targetID *string) (*SecretSummary, error) {
	resp, err := r.Vault.SetSecretTargetForPrincipal(ctx, &vaultv1.SetSecretTargetForPrincipalRequest{
		Actor: resolvers.MachineActorOf(ctx), SecretId: secretID, TargetId: deref(targetID),
	})
	if err != nil {
		return nil, err
	}
	return summaryOf(resp.GetSecret()), nil
}

// SetSecretAutomationForPrincipal is the resolver for the setSecretAutomationForPrincipal field.
func (r *mutationResolver) SetSecretAutomationForPrincipal(ctx context.Context, secretID string, disableRotation bool, disableHeartbeat bool) (*SecretSummary, error) {
	resp, err := r.Vault.SetSecretAutomationForPrincipal(ctx, &vaultv1.SetSecretAutomationForPrincipalRequest{
		Actor: resolvers.MachineActorOf(ctx), SecretId: secretID, DisableRotation: disableRotation, DisableHeartbeat: disableHeartbeat,
	})
	if err != nil {
		return nil, err
	}
	return summaryOf(resp.GetSecret()), nil
}

// PrepareSecretUse is the resolver for the prepareSecretUse field.
func (r *mutationResolver) PrepareSecretUse(ctx context.Context, secretID string, fieldKey string, argv []string, clientLabel *string, reveal *bool, runID *string, purpose *string) (*SecretUse, error) {
	resp, err := r.Vault.PrepareSecretUse(ctx, &vaultv1.PrepareSecretUseRequest{
		Actor: resolvers.MachineActorOf(ctx), SecretId: secretID, FieldKey: fieldKey, Argv: argv, ClientLabel: deref(clientLabel),
		Reveal: reveal != nil && *reveal, RunId: deref(runID), Purpose: deref(purpose),
		ActiveUsers: r.ActiveUsers.Get(ctx),
	})
	if err != nil {
		return nil, prepareRefusal(err)
	}
	return r.secretUseOf(resp.GetUse()), nil
}

// RedeemSecretUse is the resolver for the redeemSecretUse field.
func (r *mutationResolver) RedeemSecretUse(ctx context.Context, id string) (*RedeemedSecretUse, error) {
	resp, err := r.Vault.RedeemSecretUse(ctx, &vaultv1.RedeemSecretUseRequest{Actor: resolvers.MachineActorOf(ctx), UseId: id})
	if err != nil {
		return nil, err
	}
	return &RedeemedSecretUse{Use: r.secretUseOf(resp.GetUse()), Value: resp.GetValue()}, nil
}

// MachineHealth is the resolver for the machineHealth field: a trivial
// liveness probe for the machine GraphQL endpoint (no vault/identity call).
func (r *queryResolver) MachineHealth(ctx context.Context) (bool, error) {
	return true, nil
}

// MachineWhoami is the resolver for the machineWhoami field.
func (r *queryResolver) MachineWhoami(ctx context.Context) (*MachinePrincipal, error) {
	a := resolvers.MachineActorOf(ctx)
	if a.GetPrincipalKind() == vaultv1.PrincipalKind_PRINCIPAL_KIND_USER_TOKEN {
		return &MachinePrincipal{Kind: "user_token", UserID: a.GetUserId(), PrincipalID: a.GetTokenId()}, nil
	}
	return &MachinePrincipal{Kind: "service_account", PrincipalID: a.GetPrincipalId()}, nil
}

// ConnectionsForPrincipal is the resolver for the connectionsForPrincipal field.
func (r *queryResolver) ConnectionsForPrincipal(ctx context.Context) ([]*MachineConnection, error) {
	resp, err := r.Vault.ListConnections(ctx, &vaultv1.ListConnectionsRequest{})
	if err != nil {
		return nil, err
	}
	out := make([]*MachineConnection, 0, len(resp.GetConnections()))
	for _, c := range resp.GetConnections() {
		out = append(out, &MachineConnection{
			ID: c.GetId(), Name: c.GetName(), Protocol: c.GetProtocol(), Port: int(c.GetPort()),
			UseTLS: c.GetUseTls(), TargetCount: int(c.GetTargetCount()),
		})
	}
	return out, nil
}

// TargetsForPrincipal is the resolver for the targetsForPrincipal field.
func (r *queryResolver) TargetsForPrincipal(ctx context.Context, query *string, connectionID *string) ([]*MachineTarget, error) {
	resp, err := r.Vault.ListTargets(ctx, &vaultv1.ListTargetsRequest{Actor: resolvers.MachineActorOf(ctx)})
	if err != nil {
		return nil, err
	}
	q := strings.ToLower(deref(query))
	out := make([]*MachineTarget, 0, len(resp.GetTargets()))
	for _, t := range resp.GetTargets() {
		if connectionID != nil && t.GetConnectionId() != *connectionID {
			continue
		}
		if q != "" && !strings.Contains(strings.ToLower(t.GetName()+" "+t.GetHostname()+" "+t.GetDomain()), q) {
			continue
		}
		out = append(out, targetOf(t))
	}
	return out, nil
}

// SecretCheckStatus is the resolver for the secretCheckStatus field.
func (r *queryResolver) SecretCheckStatus(ctx context.Context, secretID string) (*SecretCheckStatus, error) {
	resp, err := r.Vault.GetHeartbeatStatusForPrincipal(ctx, &vaultv1.GetHeartbeatStatusForPrincipalRequest{Actor: resolvers.MachineActorOf(ctx), SecretId: secretID})
	if err != nil {
		return nil, err
	}
	return &SecretCheckStatus{
		Result:        strings.TrimPrefix(resp.GetResult().String(), "HEARTBEAT_RESULT_"),
		CheckedAtUnix: safeconv.IntFromInt64(resp.GetCheckedAtUnix()), Detail: resp.GetDetail(), Pending: resp.GetPending(),
	}, nil
}

// FindSecretsForPrincipal is the resolver for the findSecretsForPrincipal
// field. Thin bridge to vault: vault does the RACI-read filtering (RACI C)
// and returns metadata-only Secrets; this only maps them to summaries.
func (r *queryResolver) FindSecretsForPrincipal(ctx context.Context, query *string, folderID *string, typeID *string) ([]*SecretSummary, error) {
	resp, err := r.Vault.ListSecretsForPrincipal(ctx, &vaultv1.ListSecretsForPrincipalRequest{
		Actor: resolvers.MachineActorOf(ctx), Query: deref(query), FolderId: deref(folderID), TypeId: deref(typeID),
	})
	if err != nil {
		return nil, err
	}
	return summariesOf(resp.GetSecrets()), nil
}

// FoldersForPrincipal is the resolver for the foldersForPrincipal field. Vault
// does the RACI-read filtering. The gateway asks for the principal's whole
// visible tree so it can build each path, then applies the query/parentId
// filters itself with the same rules vault uses.
func (r *queryResolver) FoldersForPrincipal(ctx context.Context, query *string, parentID *string) ([]*PrincipalFolder, error) {
	resp, err := r.Vault.ListFoldersForPrincipal(ctx, &vaultv1.ListFoldersForPrincipalRequest{
		Actor: resolvers.MachineActorOf(ctx),
	})
	if err != nil {
		return nil, err
	}
	return principalFoldersOf(resp.GetFolders(), deref(query), deref(parentID)), nil
}

// SecretTypes is the resolver for the secretTypes field: the vault type
// catalog, mapped without default values.
func (r *queryResolver) SecretTypes(ctx context.Context) ([]*SecretTypeSummary, error) {
	resp, err := r.Vault.ListSecretTypes(ctx, &vaultv1.ListSecretTypesRequest{})
	if err != nil {
		return nil, err
	}
	return secretTypesOf(resp.GetTypes()), nil
}

// SecretUse is the resolver for the secretUse field.
func (r *queryResolver) SecretUse(ctx context.Context, id string) (*SecretUse, error) {
	resp, err := r.Vault.GetSecretUse(ctx, &vaultv1.GetSecretUseRequest{Actor: resolvers.MachineActorOf(ctx), UseId: id})
	if err != nil {
		return nil, err
	}
	return r.secretUseOf(resp.GetUse()), nil
}

// SecretUseRun is the resolver for the secretUseRun field.
func (r *queryResolver) SecretUseRun(ctx context.Context, runID string) ([]*SecretUse, error) {
	resp, err := r.Vault.ListPendingSecretUses(ctx, &vaultv1.ListPendingSecretUsesRequest{Actor: resolvers.MachineActorOf(ctx), RunId: runID})
	if err != nil {
		return nil, err
	}
	out := make([]*SecretUse, 0, len(resp.GetUses()))
	for _, u := range resp.GetUses() {
		out = append(out, r.secretUseOf(u))
	}
	return out, nil
}

// Automation is the resolver for the automation field. Vault's response
// carries the secret but not the new type's capabilities, so the catalog is
// read here, and only when the caller selects automation.
func (r *typeChangedSecretResolver) Automation(ctx context.Context, obj *TypeChangedSecret) (*TypeChangeAutomation, error) {
	resp, err := r.Vault.ListSecretTypes(ctx, &vaultv1.ListSecretTypesRequest{})
	if err != nil {
		return nil, err
	}
	for _, t := range resp.GetTypes() {
		if t.GetId() == obj.Secret.TypeID {
			return typeChangeAutomationOf(t, obj.Secret), nil
		}
	}
	return nil, fmt.Errorf("secret type %q is not in the catalog", obj.Secret.TypeID)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// TypeChangedSecret returns TypeChangedSecretResolver implementation.
func (r *Resolver) TypeChangedSecret() TypeChangedSecretResolver {
	return &typeChangedSecretResolver{r}
}

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type typeChangedSecretResolver struct{ *Resolver }
