// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package machineresolvers

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type FieldMappingInput struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type GeneratedSecret struct {
	Secret         *SecretSummary `json:"secret"`
	GeneratedValue *string        `json:"generatedValue,omitempty"`
}

type MachineConnection struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Protocol    string `json:"protocol"`
	Port        int    `json:"port"`
	UseTLS      bool   `json:"useTls"`
	TargetCount int    `json:"targetCount"`
}

type MachinePrincipal struct {
	Kind        string `json:"kind"`
	UserID      string `json:"userId"`
	PrincipalID string `json:"principalId"`
}

type MachineTarget struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	Hostname     string   `json:"hostname"`
	Kind         string   `json:"kind"`
	Domain       string   `json:"domain"`
	Realm        string   `json:"realm"`
	ConnectionID string   `json:"connectionId"`
	Description  string   `json:"description"`
	OwnerUserID  string   `json:"ownerUserId"`
	SecretCount  int      `json:"secretCount"`
	SSHHostKeys  []string `json:"sshHostKeys"`
}

type MachineTargetInput struct {
	ID           *string  `json:"id,omitempty"`
	Name         string   `json:"name"`
	Hostname     string   `json:"hostname"`
	Kind         *string  `json:"kind,omitempty"`
	Domain       *string  `json:"domain,omitempty"`
	Realm        *string  `json:"realm,omitempty"`
	ConnectionID string   `json:"connectionId"`
	Description  *string  `json:"description,omitempty"`
	SSHHostKeys  []string `json:"sshHostKeys,omitempty"`
}

type Mutation struct {
}

type PrincipalFolder struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	ParentID  *string `json:"parentId,omitempty"`
	Path      string  `json:"path"`
	CanAuthor bool    `json:"canAuthor"`
}

type Query struct {
}

type RedeemedSecretUse struct {
	Use   *SecretUse `json:"use"`
	Value string     `json:"value"`
}

type SecretCheckStatus struct {
	Result        string `json:"result"`
	CheckedAtUnix int    `json:"checkedAtUnix"`
	Detail        string `json:"detail"`
	Pending       bool   `json:"pending"`
}

type SecretFieldInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type SecretSummary struct {
	ID              string  `json:"id"`
	Name            string  `json:"name"`
	FolderID        string  `json:"folderId"`
	TypeID          string  `json:"typeId"`
	TargetID        *string `json:"targetId,omitempty"`
	RotationOptOut  bool    `json:"rotationOptOut"`
	HeartbeatOptOut bool    `json:"heartbeatOptOut"`
}

type SecretTypeField struct {
	Key       string `json:"key"`
	Label     string `json:"label"`
	Kind      string `json:"kind"`
	Required  bool   `json:"required"`
	Sensitive bool   `json:"sensitive"`
}

type SecretTypeSummary struct {
	ID     string             `json:"id"`
	Name   string             `json:"name"`
	Fields []*SecretTypeField `json:"fields"`
}

type SecretUse struct {
	ID            string   `json:"id"`
	SecretID      string   `json:"secretId"`
	SecretName    string   `json:"secretName"`
	FieldKey      string   `json:"fieldKey"`
	Argv          []string `json:"argv"`
	State         string   `json:"state"`
	ExpiresAtUnix int      `json:"expiresAtUnix"`
	ApprovalURL   string   `json:"approvalUrl"`
	Reveal        bool     `json:"reveal"`
	RunID         *string  `json:"runId,omitempty"`
	Confirm       bool     `json:"confirm"`
}

type TypeChangeAutomation struct {
	Rotation  TypeChangeRotation  `json:"rotation"`
	Heartbeat TypeChangeHeartbeat `json:"heartbeat"`
	Target    TypeChangeTarget    `json:"target"`
}

type TypeChangedSecret struct {
	Secret           *SecretSummary        `json:"secret"`
	FieldKeys        []string              `json:"fieldKeys"`
	MovedToNotesKeys []string              `json:"movedToNotesKeys"`
	Automation       *TypeChangeAutomation `json:"automation"`
}

type UpdatedSecretFields struct {
	Secret           *SecretSummary `json:"secret"`
	ChangedFieldKeys []string       `json:"changedFieldKeys"`
}

type TypeChangeHeartbeat string

const (
	TypeChangeHeartbeatNone     TypeChangeHeartbeat = "NONE"
	TypeChangeHeartbeatOff      TypeChangeHeartbeat = "OFF"
	TypeChangeHeartbeatNoTarget TypeChangeHeartbeat = "NO_TARGET"
	TypeChangeHeartbeatOn       TypeChangeHeartbeat = "ON"
)

var AllTypeChangeHeartbeat = []TypeChangeHeartbeat{
	TypeChangeHeartbeatNone,
	TypeChangeHeartbeatOff,
	TypeChangeHeartbeatNoTarget,
	TypeChangeHeartbeatOn,
}

func (e TypeChangeHeartbeat) IsValid() bool {
	switch e {
	case TypeChangeHeartbeatNone, TypeChangeHeartbeatOff, TypeChangeHeartbeatNoTarget, TypeChangeHeartbeatOn:
		return true
	}
	return false
}

func (e TypeChangeHeartbeat) String() string {
	return string(e)
}

func (e *TypeChangeHeartbeat) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TypeChangeHeartbeat(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TypeChangeHeartbeat", str)
	}
	return nil
}

func (e TypeChangeHeartbeat) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TypeChangeHeartbeat) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TypeChangeHeartbeat) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TypeChangeRotation string

const (
	TypeChangeRotationNone TypeChangeRotation = "NONE"
	TypeChangeRotationOff  TypeChangeRotation = "OFF"
	TypeChangeRotationOn   TypeChangeRotation = "ON"
)

var AllTypeChangeRotation = []TypeChangeRotation{
	TypeChangeRotationNone,
	TypeChangeRotationOff,
	TypeChangeRotationOn,
}

func (e TypeChangeRotation) IsValid() bool {
	switch e {
	case TypeChangeRotationNone, TypeChangeRotationOff, TypeChangeRotationOn:
		return true
	}
	return false
}

func (e TypeChangeRotation) String() string {
	return string(e)
}

func (e *TypeChangeRotation) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TypeChangeRotation(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TypeChangeRotation", str)
	}
	return nil
}

func (e TypeChangeRotation) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TypeChangeRotation) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TypeChangeRotation) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TypeChangeTarget string

const (
	TypeChangeTargetAttached     TypeChangeTarget = "ATTACHED"
	TypeChangeTargetNone         TypeChangeTarget = "NONE"
	TypeChangeTargetNotSupported TypeChangeTarget = "NOT_SUPPORTED"
)

var AllTypeChangeTarget = []TypeChangeTarget{
	TypeChangeTargetAttached,
	TypeChangeTargetNone,
	TypeChangeTargetNotSupported,
}

func (e TypeChangeTarget) IsValid() bool {
	switch e {
	case TypeChangeTargetAttached, TypeChangeTargetNone, TypeChangeTargetNotSupported:
		return true
	}
	return false
}

func (e TypeChangeTarget) String() string {
	return string(e)
}

func (e *TypeChangeTarget) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TypeChangeTarget(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TypeChangeTarget", str)
	}
	return nil
}

func (e TypeChangeTarget) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TypeChangeTarget) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TypeChangeTarget) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
